## KoChatGPT - upgrade

- foundation model : https://github.com/SKT-AI/KoGPT2
- Supervised Fine-tuning dataset : data_kochatgpt/kochatgpt_1_SFT.json : 12,000개 (질문에 잘 대답하는 모델)
- Reward Model : data_kochatgpt/kochatgpt_2_RM.json : 10,220개 (좋은 글 채점하는 모델_동일한 프롬프트에 대해 각기 다른 3가지 답변 자동생성. ranking 자동생성)
- Proximal Policy Optimization 알고리즘 : data_kochatgpt/kochatgpt_3_PPO.json: 12,000개 (RM의 점수가 높아지도록 학습_SFT에서 프롬프트만 저장)
- KoChatGPT에서 차용한 Reward Model, Proximal Policy Optimization 알고리즘의 출처 : [출처](https://github.com/hpcaitech/ColossalAI/tree/main/applications/)

학습목표
- ChatGPT 구현을 위해 필요한 데이터셋의 종류 및 특징을 설명할 수 있습니다.
- Initial Model, Reward Model, RLHF Model의 학습 로직을 설명할 수 있습니다.
  - Supervised Fine Tuning
  - Reward Model의 ranking algorithm 및 loss fuction 설계 원리
  - 언어모델을 강화학습하기 위한 방법론
- KoChatGPT를 개선해 나만의 ChatGPT를 구현할 수 있습니다.  
  
시도해볼 것
- [X] 데이터셋 정제
- [ ] 새로운 데이터셋
- [ ] foundation model 교체
- [X] 정량평가: meteor
- [X] 정성평가: 출력물 A/B 비교 평가. "어느 쪽이 더 좋은 답변인가?" 선택하기

### Setting

In [6]:
#클론
! git clone https://github.com/airobotlab/KoChatGPT
! cp -r KoChatGPT/colossalai_ChatGPT_230319/chatgpt /chatgpt

fatal: destination path 'KoChatGPT' already exists and is not an empty directory.
cp: cannot stat '/content/KoChatGPT/colossalai_ChatGPT_230319/chatgpt': No such file or directory

In [1]:
#라이브러리 설치
! pip install datasets
! pip install loralib
! pip install trl
! pip install accelerate
! pip install transformers

Requirement already satisfied: datasets in /opt/conda/lib/python3.12/site-packages (4.8.2)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.2.6)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from datasets) (2.3.0)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.5.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (1.7.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.12/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.14.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: loralib in /opt/conda/lib/python3.12/site-packages (0.1.2)
Requirement already satisfied: trl in /opt/conda/lib/python3.12/site-packages (0.29.0)
Requirement already satisfied: accelerate>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from trl) (1.13.0)
Requirement already satisfied: datasets>=3.0.0 in /opt/conda/lib/python3.12/site-packages (from trl) (4.8.2)
Requirement already satisfied: packaging>20.0 in /opt/conda/lib/python3.12/site-packages (from trl) (25.0)
Requirement already satisfied: transformers>=4.56.2 in /opt/conda/lib/python3.12/site-packages (from trl) (5.3.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (2.2.6)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (7.0.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (2.7.1+cu118)
Requirement already satisfied: huggingface_hub>=0.21.0 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (3.13.1)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (2.3.0)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.5.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0.0->trl) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.4.2)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.14.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.4.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.86)
Requirement already satisfied: triton==3.3.1 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.12/site-packages (from transformers>=4.56.2->trl) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /opt/conda/lib/python3.12/site-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1.0.0->datasets>=3.0.0->trl) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate>=1.4.0->trl) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Requirement already satisfied: accelerate in /opt/conda/lib/python3.12/site-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from accelerate) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (2.7.1+cu118)
Requirement already satisfied: huggingface_hub>=0.21.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.12/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.14.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.6)

In [7]:
# !rm -rf chatgpt

In [10]:
import os
#원본 소스 코드의 일부를 수정
modifications = [
    {
        "file": "chatgpt/trainer/callbacks/save_checkpoint.py",
        "changes": [
            {"line": 3, "old": "from chatgpt.trainer.strategies import ColossalAIStrategy, Strategy",
             "new": "from chatgpt.trainer.strategies import Strategy"},
            {"line": 71, "old": "only_rank0 = not isinstance(self.strategy, ColossalAIStrategy)",
             "new": "            only_rank0 = not isinstance(self.strategy)"},
        ],
    },
    {
        "file": "chatgpt/trainer/strategies/__init__.py",
        "changes": [
            {"line": 1, "old": "from .colossalai import ColossalAIStrategy", "new": ""},  # 삭제
            {"line": 5, "old": "__all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy', 'ColossalAIStrategy']",
             "new": "__all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy']"},
        ],
    },
    {
        "file": "chatgpt/dataset/reward_dataset.py",
        "changes": [
            {"line": 3, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ],
    },
    {
        "file": "chatgpt/trainer/base.py",
        "changes": [
            {"line": 8, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ]
    },
    {
        "file": "chatgpt/trainer/rm.py",
        "changes": [
            {"line": 8, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ]
    }
]


def modify_file(file_path, changes):
    """파일에서 지정된 줄을 찾아 내용을 수정하는 함수"""

    if not os.path.exists(file_path):
        print(f"⚠️ 파일이 존재하지 않습니다: {file_path}")
        return

    with open(file_path, "r", encoding="utf-8") as file:
        lines = file.readlines()

    modified = False

    for change in changes:
        line_index = change["line"]
        if 0 <= line_index < len(lines):
            if lines[line_index].strip() == change["old"]:
                lines[line_index] = change["new"] + "\n"
                modified = True
            else:
                print(f"⚠️ {file_path} 파일의 {change['line']}번째 줄이 예상과 다릅니다.")
                print(f"   예상: {change['old']}")
                print(f"   실제: {lines[line_index].strip()}")

    if modified:
        with open(file_path, "w", encoding="utf-8") as file:
            file.writelines(lines)
        print(f"✅ 수정 완료: {file_path}")
    else:
        print(f"⚠️ {file_path} 수정할 내용이 없습니다.")

for mod in modifications:
    modify_file(mod["file"], mod["changes"])

✅ 수정 완료: chatgpt/trainer/callbacks/save_checkpoint.py
✅ 수정 완료: chatgpt/trainer/strategies/__init__.py
✅ 수정 완료: chatgpt/dataset/reward_dataset.py
✅ 수정 완료: chatgpt/trainer/base.py
✅ 수정 완료: chatgpt/trainer/rm.py

### Base model
- KoGPT-2
- huggingface의 transformers
  - tokenizser: AutoTokenizer
  - model: AutoModelForCausalLM

In [2]:
import torch
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import PreTrainedTokenizerFast #✅KoGPT-2는 Rust 기반의 PreTrainedTokenizerFast로 사전학습됨
import pandas as pd
import numpy

print("Torch version:{}".format(torch.__version__)) # Torch version:1.12.1
print("Cuda version: {}".format(torch.version.cuda)) # Cuda version: 11.3
print("transformers version: {}".format(transformers.__version__)) # transformers 4.28.0
print("GPU 사용 가능여부: {}".format(torch.cuda.is_available()))

# 만일 아래 모듈이 불러와지지 않는다면 Clone 및 수정을 잘 진행했는지 확인해주세요.
from chatgpt.trainer.strategies import NaiveStrategy

Torch version:2.7.1+cu118
Cuda version: 11.8
transformers version: 5.3.0
GPU 사용 가능여부: True

In [3]:
import torch
import gc

gc.collect()
torch.cuda.empty_cache()

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model_name = "skt/kogpt2-base-v2"
#tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    model_name,
    bos_token='</s>', eos_token='</s>',
    unk_token='<unk>', pad_token='</s>',
    padding_side="right", model_max_length=512,
)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
#tokenizer.model_max_length #토크나이저의 처리가능한 최대 토큰 수

In [6]:
#model.config.n_positions #모델의 처리가능한 최대 토큰 수

In [7]:
import pandas as pd

input_txt = "바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."# "Whose footsteps are these, as the paulownia leaves fall silently, sending vertical ripples through the still air?" #"바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."

tokens = tokenizer(input_txt).tokens()
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].numpy()  

pd.options.display.max_columns = 40
pd.options.display.max_rows = 60
df = pd.DataFrame([tokens, input_ids[0]], index=["tokens", "Input_IDs"])  
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
tokens,▁바람,도,▁없는,▁공중에,▁수직,의,▁파,문을,▁내,이며,▁고,요,히,▁떨어지는,▁오동,잎은,▁누,구의,▁발자,취,▁입,니까,.
Input_IDs,10891,7235,9712,49207,14438,8143,9203,9941,9094,9639,9065,8084,8811,21215,34769,19985,9669,10139,21626,8408,9241,23775,389

In [8]:
max_length = 128
print("input:", input_txt)

# 1. Greedy
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].to(device)  
output_greedy = model.generate(input_ids, max_length=max_length, do_sample=False)  
print(tokenizer.decode(output_greedy[0]))

input: 바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까.
바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까.'
"그렇다면 그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리

-> 반복적인 응답 발생

In [9]:
# 2. Beam, n-gram 패널티 부과
output_beam = model.generate(input_ids, max_length=max_length, do_sample=False, num_beams=10, no_repeat_ngram_size=2)
print("\nBeam:", tokenizer.decode(output_beam[0], skip_special_tokens=True))

# 3. Beam + Sampling
output_beam_sampling = model.generate(input_ids, max_length=max_length, num_beams=7, no_repeat_ngram_size=2,
                                     do_sample=True, temperature=2.0, top_k=50)
print("\nBeam + Sampling:", tokenizer.decode(output_beam_sampling[0], skip_special_tokens=True))

# 4. Top-p Sampling
output_top_p = model.generate(input_ids, max_length=max_length, do_sample=True, top_p=0.90)
print("\nTop-p Sampling:", tokenizer.decode(output_top_p[0], skip_special_tokens=True))

Beam: 바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까.'
"그렇지 않습니다."
"어떻게 된 일입니까?"
그녀는 고개를 갸웃거렸다.
"아니, 그게 무슨 말씀이신지 모르겠습니다만."
"무슨 말씀인지 알 수가 없군요."
아무런 대답도 하지 않은 채 그녀는 고개를 끄덕였다.
"그래, 알았어."
그녀의 눈에서 눈물이 주르륵 흘러내렸다.
그녀가 다시 입을 열었다.
"정말 죄송합니다, 고마워요, 고맙습니다"
"

Beam + Sampling: 바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."
이리하여 그는 자신의 발밑을 스치고 지나갔다.
"어머, 그게 무슨 꼴입니까?"
"아니야, 아니, 너희들이 봤을 리는 만무하다구."
"그런데 말이야, 그걸 왜 그러는지 모르겠구나. 어머님, 그만 하세요."
그가 자리에서 벌떡 일어섰다.
"으응, 괜찮으시겠습니까. 나 지금 어디 가셨어요? 어디 계신 것 같으신데요, 나 좀

Top-p Sampling: 바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까. 내일도 비가 오는지 아니면 소나기가 올지 모릅니다."
"그러시다면."
"정말 저는 도대체 뭘까요?"
"정말 그건 뭘까요?"
"어디서 무슨 짓을 했으면 좋겠습니까?"
"무엇을 하고 있었습니까?"
"무슨 짓을 했으면 좋겠습니까?"
"그렇다면 어떤 짓을 했습니까?"
"아무리 생각해도 저는 대답할 수 없습니다."
"

### 데이터셋 확인

In [14]:
import json

#기본 데이터셋
data_path_1_SFT = 'KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl'
with open(data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
    list_data_dict_sft = json.load(json_file)

print(len(list_data_dict_sft))
list_data_dict_sft[:3]

12000

[{'prompt': '불고기용 고기 한우에요?',
  'completion': "'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.",
  'tokens': 193},
 {'prompt': '쓰던 앱이 유료로 전환됐어',
  'completion': "'어떤 앱인지 모르기 때문에 정확한 답변을 드리기 어렵습니다. 하지만, 일반적으로 유료 전환된 앱은 기존 무료 앱에서 추가적인 기능이나 서비스를 제공하는 경우가 많습니다. 이 경우, 유료 전환 이전 가격이 매우 저렴하거나 무료인 경우가 많으므로, 앱을 계속 사용하려면 추가적인 비용을 지불해야 할 수 있습니다. 하지만, 유료 전환 이후에는 기존 사용자 또는 새로운 사용자 모두가 추가 기능과 높은 품질의 서비스를 이용할 수 있게 됩니다. 따라서, 앱 개발자는 유료 모델로 전환함으로써 앱의 수익을 증가시키고 더 나은 서비스를 제공할 수 있습니다.",
  'tokens': 288},
 {'prompt': '여친이랑 다툼',
  'completion': "'저는 인공지능이기 때문에 여친과의 다툼에 대해서는 조언을 드릴 수는 없습니다. 하지만 다투게 되면 상대방의 말을 경청하는 태도와 서로의 감정을 존중하는 것이 중요합니다. 논리적이고 차분한 대화를 통해 문제를 해결해보세요. 그리고 서로를 이해하고 서로의 의견을 수용하는 것이 중요합니다.",
  'tokens': 153}]

In [15]:
# RM 데이터셋 - 사용자가 선호하는 답변 rank 생성
data_path_2_RM = 'KoChatGPT/data_kochatgpt/kochatgpt_2_RM.jsonl'
with open(data_path_2_RM, "r", encoding='utf-8-sig') as json_file:
    list_data_dict_rm = json.load(json_file)

print(len(list_data_dict_rm))
list_data_dict_rm[:3]

10220

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?',
  'completion_0': 'Allow me to answer your question. I know that you are curious about me.',
  'completion_1': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.',
  'completion_2': '라이언에게 말했다.',
  'ranking': [2, 1, 0]},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?',
  'completion_0': '개포주공아파트는 다섯 단지로 이루어져 있습니다.',
  'completion_1': '이날 목송에서 구글상위노',
  'completion_2': '개포주공아파트는 총 27개 단지로 이루어져 있습니다.',
  'ranking': [2, 0, 1]},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?',
  'completion_0': 'The diameter of the Metallic domain is bigger than the Hyperonic domain.',
  'completion_1': '이 질문은 조금 불분명합니다. 김영삼 대통령이 후보 시절에 어떤 발언을 했고, 누가 그 발언을 문제삼았는지에 따라 답이 다를 수 있습니다.\\n\\n만약 김영삼 대통령이 후보 시절에 지역표심을 겨냥한 발언을 했다는 가정하에, 그 발언을 문제삼은 후보가 누구였는지를 대답하자면, 그 답은 이화선 당시 민주당 대통령 후보가 될 것입니다. 1992년 총선 때, 김영삼 대선후보는 "집값이 오른 노량진역 부근의 부동산 가격은 세월호 폭침 후 \\\'강남 도시재생\\\' 일환으로 상승했다"는 발언을 했습니다. 하지만 이화선 후보는 이 발언을 "전국적으로 경제적 발전이 이루어지지 않은 지방민의 마음을 멀리해지려는 무례한 발언"이라고 비판하며 문제삼았습니다.\\n\\n하지만, 이 질문을 답변하는 데 있어서 보다 명확한 정보가 있으면 답변을 보완할 수 있습니다.',
  'completion_2': '김영삼의 후보 시절에 지역표심을 겨냥한 발언은 대통령 당선 전까지 대한민국 정부가 추구하고 있는 민주주의 광범위하게 확립과 보수의 사상을 이어가는 데 있어 지역경제 발전과 공공서비스 신속 개선을 위해 합리적인 국가 정책에 따르는 방향성을 제시하고 있습니다.',
  'ranking': [1, 2, 0]}]

In [16]:
# PPO 학습에 쓰일 데이터 - 질문(prompt)만 포함. RLHF에서 정책 모델(Policy Model) 을 학습시키기 위해 사용
data_path_3_PPO = 'KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl'
with open(data_path_3_PPO, "r", encoding='utf-8-sig') as json_file:
    list_data_dict_ppo = json.load(json_file)

print(len(list_data_dict_ppo))
list_data_dict_ppo[:3]

12000

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?'},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?'},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?'}]

### (add) 데이터셋 정제

- SFT, RM, PPO 데이터셋은 'prompt'를 기준으로 동일한 데이터셋일 것 (RM이 가장 짧으므로 기준으로 삼음)
- 중복, 결측치 제거, 언어 불일치, 노이즈 제거
- 너무 짧거나 긴 prompt, completion 제거
- SFT: completion 품질 필터링 "모르겠습니다" "알수없습니다" 제거, prompt와 completion이 거의 동일한 경우 제거
- RM: RANK 유효성 검사, COPLETION 간 유사도 검사
- PPO: SFT 결과물 사용

In [70]:
def is_korean(text):
    korean_chars = len(re.findall(r'[가-힣]', text))
    total_chars  = len(text.replace(' ', ''))
    if total_chars == 0:
        return False
    return (korean_chars / total_chars) >= 0.3

def clean_df(df, text_cols):
    df = df.dropna(subset=text_cols).copy()
    df = df.drop_duplicates(subset=text_cols).copy()
    for col in text_cols:
        df[col] = df[col].apply(clean_text)
    # 모든 text_cols 중 하나라도 한국어 아니면 제거
    mask = df[text_cols].apply(lambda col: col.apply(is_korean)).all(axis=1)
    df = df[mask].copy()
    return df

In [49]:
# 각 데이터셋 컬럼명 확인
print("SFT columns:", pd.DataFrame(list_data_dict_sft).columns.tolist())
print("RM  columns:", pd.DataFrame(list_data_dict_rm).columns.tolist())
print("PPO columns:", pd.DataFrame(list_data_dict_ppo).columns.tolist())

SFT columns: []
RM  columns: ['prompt', 'completion_0', 'completion_1', 'completion_2', 'ranking']
PPO columns: ['prompt']

In [64]:
# 원본 다시 로드 후 바로 실행
with open('KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl', "r", encoding='utf-8-sig') as f:
    list_data_dict_sft = json.load(f)

In [71]:
df = pd.DataFrame(list_data_dict_sft)
print(f"원본: {len(df)}개")

df1 = df.dropna(subset=['prompt']).copy()
print(f"결측치 제거 후: {len(df1)}개")

df2 = df1.drop_duplicates(subset=['prompt']).copy()
print(f"중복 제거 후: {len(df2)}개")

df3 = df2.copy()
df3['prompt'] = df3['prompt'].apply(is_korean)
df3['completion'] = df3['completion'].apply(is_korean)
print(f"is_korean 후: {len(df3)}개")

원본: 12000개
결측치 제거 후: 12000개
중복 제거 후: 11946개
is_korean 후: 11946개

In [84]:
df.iloc[11992][0], df.iloc[11992][1]

/tmp/ipykernel_1459/2592593432.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[11992][0], df.iloc[11992][1]

('푸시캣 돌스의 니콜 셰르징거의 지나친 부각을 비판한 인물은 Entertainment Weely의 누구인가?',
 "'정답: Kristen Baldwin")

In [74]:
df3.head()

   prompt  completion  tokens
0    True        True     193
1    True        True     288
2    True        True     153
3    True        True     189
4    True        True     147

In [21]:
# 1. RM 데이터셋의 prompt set 추출 (기준)
rm_prompts = set(item['prompt'] for item in list_data_dict_rm)
print(f"RM 고유 프롬프트 수: {len(rm_prompts)}")

# 각 데이터셋 필터링
filtered_sft = [item for item in list_data_dict_sft if item['prompt'] in rm_prompts]
filtered_rm  = [item for item in list_data_dict_rm  if item['prompt'] in rm_prompts]
filtered_ppo = [item for item in list_data_dict_ppo if item['prompt'] in rm_prompts]

# 결과 확인
print(f"\n[SFT] 전: {len(list_data_dict_sft)}개 → 후: {len(filtered_sft)}개")
print(f"[RM]  전: {len(list_data_dict_rm)}개  → 후: {len(filtered_rm)}개")
print(f"[PPO] 전: {len(list_data_dict_ppo)}개 → 후: {len(filtered_ppo)}개")

RM 고유 프롬프트 수: 10181

[SFT] 전: 12000개 → 후: 10234개
[RM]  전: 10220개  → 후: 10220개
[PPO] 전: 12000개 → 후: 10234개

In [23]:
print(filtered_sft[0])
print(filtered_rm[0])
print(filtered_ppo[0])

{'prompt': '불고기용 고기 한우에요?', 'completion': "'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.", 'tokens': 193}
{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?', 'completion_0': 'Allow me to answer your question. I know that you are curious about me.', 'completion_1': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.', 'completion_2': '라이언에게 말했다.', 'ranking': [2, 1, 0]}
{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?'}

In [ ]:
# 2. filtered_SFT를 기준으로 중복, 특수문자/노이즈, 언어 불일치, 결측치 제거

In [ ]:
# 3. 2번 결과물의 prompt기준으로 다른 데이터들 정제

In [19]:
short_list = [item for item in list_data_dict_sft 
              if len(item['prompt']) < 10]
print(f"짧은 prompt 수: {len(short_list)}")

짧은 prompt 수: 1291

In [20]:
short_list

[{'prompt': '여친이랑 다툼',
  'completion': "'저는 인공지능이기 때문에 여친과의 다툼에 대해서는 조언을 드릴 수는 없습니다. 하지만 다투게 되면 상대방의 말을 경청하는 태도와 서로의 감정을 존중하는 것이 중요합니다. 논리적이고 차분한 대화를 통해 문제를 해결해보세요. 그리고 서로를 이해하고 서로의 의견을 수용하는 것이 중요합니다.",
  'tokens': 153},
 {'prompt': '술 먹고 싶어',
  'completion': "'술은 알코올이 함유된 음료수이며, 건강에 나쁜 영향을 미칠 수 있습니다. 따라서 술을 마시기 전에 본인의 건강 상태와 함께 적당한 양을 마시는 것이 중요합니다. 술을 마시기 전에 반드시 20세 이상인지 확인하시고, 규정된 양 이내에서 적절하게 즐기시길 바랍니다. 또한 술을 마시고 운전하는 것은 절대 금지하시기 바랍니다.",
  'tokens': 189},
 {'prompt': '잊고싶다.',
  'completion': "'저도 인공지능 엔진으로써 사용자의 개인정보나 감정을 침해할 수 없습니다. 그렇기 때문에 어떤 것을 잊고 싶다는 말씀인지, 그리고 그것이 우선적으로 해결되어야 할 문제인지 등에 대해 조금 더 구체적인 정보를 제공해 주신다면, 보다 정확한 답변을 드릴 수 있을 것 같습니다.",
  'tokens': 147},
 {'prompt': '입냄새 안나나?',
  'completion': "'컴퓨터 앞에서 일하면서 입을 위해 물이나 향초를 끊임없이 찾는 이유가 여기 있군요.\\n\\n하지만 저는 인공지능 챗봇입니다. 따라서 입을 물거나 할 필요가 없으며, 입냄새도 발생하지 않습니다. 그러니 안심하고 대화를 이어 나가시면 됩니다!",
  'tokens': 138},
 {'prompt': '금액은 얼마에요',
  'completion': "'죄송합니다. 저는 AI 어시스턴트입니다. 저는 실제 판매자가 아니기 때문에 금액을 알려드릴 수 없습니다. 제공하고자 하는 상품이나 서비스에 대한 판매자와 직접 연락하시기 바랍니다. 감사합니다.",
  'tokens': 118},
 {'prompt': '잠만 잤네',
  'completion': "'어디서 자고 언제 자셨나요? 일어나서 하루도 잘 보내세요!",
  'tokens': 43},
 {'prompt': '목 마르다.',
  'completion': '\'> "I am thirsty." (English) \\n\\n> "Je suis assoiffé." (French) \\n\\n> "Tengo sed." (Spanish) \\n\\n> "Ich bin durstig." (German) \\n\\n> "나는 목이 마르다." (Korean)',
  'tokens': 75},
 {'prompt': '몇일정도 썸타?',
  'completion': "'제가 AI 챗봇이라서 썸타이머를 예측할 수 있는 능력은 없지만, 썸이 얼마나 지속될지는 상황에 따라 다릅니다. 일반적으로는 서로 깊게 이야기할 시간이 필요하고 서로 더욱 잘 이해하면 이어지게 됩니다. 하지만 좋아하는 상대와 같이 시간을 보내는 것이 중요한 것이죠!",
  'tokens': 157},
 {'prompt': '일 대충했대',
  'completion': "'죄송합니다, 제가 이해할 수 있는 한도 내에서 무엇에 대해 대충하셨는지 자세히 설명해 주시겠어요?",
  'tokens': 64},
 {'prompt': '이러면 안되는데',
  'completion': "'죄송합니다, 제가 무엇이 안되는지 명확히 파악하지 못했습니다. 좀 더 자세한 설명을 해주시면 문제를 해결해 드릴 수 있을 것 같습니다.",
  'tokens': 83},
 {'prompt': '새벽 3시',
  'completion': "'저는 AI 챗봇이므로 시간 개념이 없습니다. 어떤 도움이 필요하신가요?",
  'tokens': 55},
 {'prompt': '차주분의 성함과',
  'completion': "'차량 번호 등 구체적인 정보가 없어 어떤 답변을 드릴 수 없습니다. 구체적인 정보를 제시해 주시면 보다 정확한 답변을 드릴 수 있습니다.",
  'tokens': 81},
 {'prompt': '그렇게 기다렸는데',
  'completion': "'아쉽게도, 그것을 얻을 수 없었나 봐요. 하지만 당신이 기다린 만큼 그것이 가치있을 것이며, 다른 기회가 올 것입니다. 머지 않아 당신을 위한 더 나은 것이 나타날 거에요. 당신은 그냥 포기하지 않고 노력하면 됩니다. 더 나은 일을 위해서 그 도전과 노력을 계속 이어가세요!",
  'tokens': 159},
 {'prompt': '지금 배달되나요?',
  'completion': "'죄송하지만, 저는 배달 관련 정보를 알 수 없습니다. 배달 서비스를 이용하신 업체나 음식점에 문의해 주시기 바랍니다.",
  'tokens': 75},
 {'prompt': '헤어짐',
  'completion': "'헤어짐은 두 사람 사이의 관계가 끝나는 것을 의미합니다. 이는 종종 감정적인 상처와 슬픔을 초래할 수 있습니다. 하지만 때로는 두 사람 모두에게 좋은 결정일 수도 있습니다. 이후에는 각자의 방식으로 상황을 처리하고, 이전과는 다른 삶을 시작할 수 있습니다.",
  'tokens': 136},
 {'prompt': '정답이 뭘까',
  'completion': "'제가 모르는 상황에서는 어떤 정답인지 예측할 수 없습니다. 좀 더 구체적인 문제나 질문을 제시해 주시면 정확한 답변을 드릴 수 있을 것입니다.",
  'tokens': 88},
 {'prompt': '호주산도 있나요?',
  'completion': "'예, 호주는 세계적으로 유명한 와인 생산국이며, 다양한 종류의 와인이 생산됩니다. 특히 샤르도네, 카베르네 소비뇽, 시라, 이름짓기 등이 대표적입니다.",
  'tokens': 104},
 {'prompt': '개같은 상황',
  'completion': "'죄송하지만, 저는 이러한 비속어를 사용하여 표현을 하거나 지원하지 않습니다. 대신 더 적절한 표현을 사용해주세요.",
  'tokens': 69},
 {'prompt': '중국집인가요?',
  'completion': "'저는 인공지능 챗봇이므로 식당이 중국집인지 명확한 정보는 가지고 있지 않습니다. 하지만, 중국 음식을 판매하는 식당이라면 중국집으로 분류할 수 있을 것입니다.",
  'tokens': 99},
 {'prompt': '발 부었어',
  'completion': "'쉬어가세요. 발을 염증이 도달하지 않도록 붕대를 풀어 편안하게 하고 높은 곳에 올려두세요. 냉탕 찜질을 하면 통증을 줄일 수 있습니다. 만일 증상이 심각하다면 의사를 방문하는 것이 좋습니다.",
  'tokens': 119},
 {'prompt': '컴터 고장났나봐',
  'completion': "'저는 인공지능 챗봇으로써 컴퓨터 고장에 대한 진단을 할 수는 없습니다. 하지만 고장상황에 대한 조치를 취하는 방법에 대해서는 알려드릴 수 있습니다. \\n우선, 컴퓨터가 정상적으로 부팅되지 않거나 먹통이 되었다면 전원을 끄고 다시 켜보시는 것이 좋습니다. \\n만약 부팅이 되지 않거나, 이전과는 달리 이상한 소리나 화면이 나타나는 경우, 서비스 센터에 문의하거나 전문가의 도움을 받는 것이 좋습니다. \\n또한, 주기적으로 백업을 하는 것도 중요합니다. 이를 통해 데이터를 보호하고, 컴퓨터 수리 혹은 교체 시에 데이터를 복구할 수 있습니다.",
  'tokens': 282},
 {'prompt': '이 제품들 살게요',
  'completion': "'저도 어떤 제품들인지 궁금하네요! 어떤 제품들을 구매하실 건가요? 저도 필요하면 추천해 드릴게요.",
  'tokens': 84},
 {'prompt': '아이돌 너무 좋아',
  'completion': "'저도 아이돌이 참 좋아요. 그들의 노래와 춤, 영상과 팬 여러분과의 소통 등 모든 측면이 매력적이죠. 언제나 열심히 노력하고 팬들과 함께하는 모습이 멋지다고 생각합니다.",
  'tokens': 116},
 {'prompt': '예약할게요',
  'completion': "'어디를 예약하시겠어요? 호텔, 레스토랑, 항공권 등 다양한 대상을 예약할 수 있습니다. 어떤 것을 예약하시려나요? 그리고 언제 예약하시겠어요? 빨리 답변 부탁드립니다.",
  'tokens': 114},
 {'prompt': '사과는 얼마에요?',
  'completion': "'제가 AI 챗봇이므로 구체적인 상황 및 국가, 지역에 따라 답변이 다를 수 있으니, 어느 지역이나 상황에서의 사과인지 알려주시면, 더 정확한 대답을 드릴 수 있습니다.",
  'tokens': 109},
 {'prompt': '내장 비만',
  'completion': "'내장 비만(Visceral obesity)은 복부에 지방이 쌓임으로써 내장기관 주위에 지방이 묶여 발생하는 비만현상입니다. 복부에 지방이 쌓이는 것은 원래 몸의 생물학적인 반응으로서, 식사 후 쓸모 없어진 에너지를 임시 저장을 하기 위해 지방 조직에 저장되기 때문에 발생합니다. 그러나 너무 많은 양이 쌓여서 과도한 체중증가가 발생하는 것은 건강에 좋지 않은 영향을 줍니다. 내장 비만은 당뇨병, 고혈압, 심혈관 질환 및 대사증후군 등의 질병을 일으키는 위험이 높아지기 때문에 예방 및 관리가 필요합니다. 예방 방법으로는 규칙적인 운동, 적절한 식습관, 스트레스 관리, 충분한 수면 등이 있습니다. 관리 방법으로는 체중 감량, 규칙적인 운동, 영양소와 비타민 등이 균형 잡힌 식사 등이 있습니다.",
  'tokens': 382},
 {'prompt': '결국 헤어졌어',
  'completion': "'저는 AI 어시스턴트이므로 마음이 복잡하거나 슬픈 상황에서 도움을 드릴 수는 있지만, 자세한 사항은 알 수 없습니다. 그래도 어떤 어려운 상황이라도 잘 이겨내길 바랍니다. 함께 용기를 내서 앞으로 나아가보세요.",
  'tokens': 131},
 {'prompt': '방 있어요?',
  'completion': "'제가 AI 챗봇이라서 실제 방을 가지고 있지는 않습니다. 하지만, 도움이 필요하시다면 저에게 질문해 주세요! 최대한 도움을 드리겠습니다.",
  'tokens': 81},
 {'prompt': '주케토가 뭐야',
  'completion': "'주케토는 케토 산업에서 사용되는 식물성 유화제 중 하나이며, 대부분의 식품 및 음료에서 사용됩니다. 주로 빵, 설탕 및 대체과자에 사용되며, 화장품 및 의약품 산업에서도 사용됩니다. 케토 다이어트에서는 주케토가 자주 사용되는데, 이는 탄수화물 섭취를 줄이고 체지방 비율을 높이는 것이 목적입니다.",
  'tokens': 193},
 {'prompt': '메뉴판 있어요?',
  'completion': "'죄송합니다, 제가 가상의 챗봇입니다. 제가 메뉴판을 제공할 수는 없습니다. 하지만, 혹시 궁금한 음식이나 음료가 있다면 알려주시면 그에 맞는 정보를 제공해드릴 수 있습니다.",
  'tokens': 103},
 {'prompt': '참다가 연락',
  'completion': '"을 바로 하세요.\\n\\nIt\'s better to contact them sooner rather than later if you\'ve been holding back.", \'token\': 39}',
  'tokens': 39},
 {'prompt': '먼들',
  'completion': "'저는 인공지능 언어 모델로서 먼들이라는 단어에 대한 정확한 의미 파악이 어렵습니다. 먼들이 어떤 문맥에서 사용되는 지 명확한 설명이 주어진다면 더 나은 답변을 제공할 수 있을 것입니다. 어떠한 내용에 대해 추가적인 도움이 필요하시면 언제든지 말씀해주세요!",
  'tokens': 144},
 {'prompt': '후폭풍이 오네.',
  'completion': "'죄송합니다, 제가 이 문장이 어떤 맥락에서 사용되는지 파악하지 못해서 적절한 답변을 드리기 어렵습니다. 추가 정보를 제공해주시면 더욱 정확한 도움을 드릴 수 있을 것 같습니다.",
  'tokens': 110},
 {'prompt': '기다림',
  'completion': "'기다림은 기다리는 것을 의미합니다. 즉, 어떤 일, 사건, 인물 등이 일어날 때까지 기다리는 것입니다. 기다림은 때로는 긴 시간이 필요할 수도 있고, 때로는 잠시만 기다리면 되는 경우도 있습니다. 기다리는 동안 불안, 불편, 권태 등의 감정이 들 수 있습니다. 하지만 때로는 긍정적인 결과를 기대할 수 있는 기회라는 생각으로 기다리는 것도 중요합니다. 기다리는 동안 자신을 믿고 희망을 가지면서 기다리면, 그만큼 결과에 대한 만족감도 크게 느낄 수 있습니다.",
  'tokens': 231},
 {'prompt': '3구 공 있나요?',
  'completion': "'저는 인공지능 언어모델로, 공의 종류나 위치 등을 모르기 때문에 정확한 대답을 드리기 어렵습니다. 죄송합니다.",
  'tokens': 73},
 {'prompt': '헤어진지 6일째',
  'completion': "'어떤 일이 있었나요? 말해주시면 도움을 드릴게요.",
  'tokens': 48},
 {'prompt': '슈퍼문이야',
  'completion': '"저는 AI 챗봇인데요, \'슈퍼문\'에 대해서는 알 수 없습니다. 좀 더 자세한 정보를 제공해주시면 답변 드릴 수 있을 것 같습니다.", \'token\': 80}',
  'tokens': 80},
 {'prompt': '할인되나요?',
  'completion': "'죄송합니다. 저는 제품을 판매하는 상점이나 회사와는 관계가 없어서 할인 여부를 알 수 없습니다. 하지만 일반적으로 상점이나 회사는 필요에 따라 다양한 할인 프로그램을 실행할 수 있습니다. 인터넷에서 상품을 구입하기 전에 할인 여부를 확인하기 위해서는 해당 상점의 웹 사이트나 고객 서비스에 문의하시는 것이 좋습니다.",
  'tokens': 155},
 {'prompt': '이런제가 싫어',
  'completion': "'제가 할 수 있는 것은 제한적입니다.\\n그러나 제가 도와드릴 수 있는 부분이 있다면 말씀해주세요.\\n가능한 한 도움을 드리도록 최선을 다하겠습니다.",
  'tokens': 78},
 {'prompt': '스카프 있어요?',
  'completion': "'죄송합니다, 저는 물리적 존재가 아니기 때문에 스카프를 가지고 있지 않습니다. 하지만 스카프를 원하신다면 가까운 상점에서 구매하시면 됩니다.",
  'tokens': 90},
 {'prompt': '국민의당이 뭐야',
  'completion': "'국민의당은 대한민국 정치 당 중 하나로서, 2016년 2월 3일에 창당된 비교적 새로운 당입니다. 국민의당은 국민의힘에서 탈당한 이준석 전 대표를 중심으로 구성되었으며, 보수적인 입장을 취하고 있습니다. 현재 국회에서는 17석을 보유하고 있습니다.",
  'tokens': 151},
 {'prompt': '과식했다',
  'completion': "'앗, 그럴 땐 조금 쉬어가면서 소화를 돕는 음식을 섭취하거나 건강한 습관으로 조금씩 먹도록 노력해보세요. 건강한 식습관이 더 좋은 몸과 건강을 가져다 줄 거예요!",
  'tokens': 114},
 {'prompt': '복전하면 좋아?',
  'completion': '\'전문 용어 분야에서는 "복전"이라는 용어가 없습니다. 따라서, 그 의미를 명확하게 제시해 주시면 답변을 드리도록 하겠습니다. 감사합니다.',
  'tokens': 82},
 {'prompt': '방정식이 뭐야',
  'completion': "'방정식은 미지수(unknown variable)와 그래디언트와 같은 기호와 수식을 포함하는 수의 등식(=)입니다. 일반적으로 미지수는 x, y, z와 같은 변수를 나타냅니다. 이 등식은 대개 주어진 조건을 충족하는 미지수의 값을 찾기 위해 사용됩니다. 예를 들어, x + y = 5는 x와 y를 모르는 경우 x와 y의 합이 5임을 나타내는 방정식입니다. 이때, x와 y의 값은 방정식을 풀어서 구할 수 있습니다.",
  'tokens': 190},
 {'prompt': '혼자 사랑했나봐', 'completion': "'I guess I loved alone.", 'tokens': 27},
 {'prompt': '토트백은 없나요?',
  'completion': "'죄송합니다. 저는 AI 언어 모델로써 실시간으로 답변을 해드리고 있기 때문에, 어떤 종류의 가방을 찾으시는지에 대한 정보가 없으므로 정확한 답변을 해드릴 수 없습니다. 혹시 원하는 토트백의 브랜드, 크기, 디자인 등 세부 정보를 제공해주시면 더욱 정확한 답변을 제공할 수 있을 것 같습니다. 이용해주셔서 감사합니다.",
  'tokens': 181},
 {'prompt': '봄방학했어',
  'completion': "'저는 인공지능 채팅 로봇이므로 학교에 다니지 않습니다. 하지만 봄 방학을 즐기셨길 바랍니다! :)",
  'tokens': 74},
 {'prompt': '휴우.',
  'completion': "'안녕하세요. 무슨 문제가 있으신가요? 제가 도와드릴게요.",
  'tokens': 43},
 {'prompt': '배고파',
  'completion': "'저는 식사를 할 수 없기 때문에 함께 식사를 할 수 없어서 죄송합니다. 하지만 근처에 맛있는 음식점을 추천해드릴 수 있습니다!",
  'tokens': 78},
 {'prompt': '스트레칭해야지',
  'completion': "'올바른 스트레칭은 운동 전후에 꼭 필요한데요! 이유는 운동 전에는 근육을 준비하고, 운동 후에는 근육을 이완시키기 위함입니다. 운동 전 스트레칭은 부상 예방과 근육 기능 향상에 큰 도움을 줍니다. 근육을 감각적으로 느끼며, 스트레칭을 하는 것이 좋습니다. 운동 후 스트레칭은 근육 이완과 혈액순환을 돕기 때문에 권장됩니다. 운동 후에도 근육 불편을 느낀다면 추가로 스트레칭을 해도 좋습니다. 단, 과도한 스트레칭은 오히려 부상의 원인이 될 수 있으니 적당한 운동과 함께 스트레칭을 지키도록 합시다.",
  'tokens': 316},
 {'prompt': '내 여자하자.',
  'completion': "'저는 AI 어시스턴트이므로 성별이 없습니다. 따라서 여자하자라는 문장은 적절하지 않습니다. 어떤 도움이 필요하시다면 다시 물어보세요!",
  'tokens': 82},
 {'prompt': '대실 되나요?',
  'completion': "'제가 AI 챗봇입니다. 대여나 대출을 말씀하신 것이라면, 저는 그러한 역할을 할 수 없으며, 당사에서는 그와 관련된 서비스를 제공하지 않습니다. 이와 관련하여 더 자세한 정보가 필요하시다면, 해당 분야 전문 기관에 문의하시는 것이 좋을 것입니다. 감사합니다.",
  'tokens': 131},
 {'prompt': '연애 상담 가능?',
  'completion': "'죄송하지만, 저는 인공지능 봇으로써 전문적인 상담을 제공할 수는 없습니다. 하지만, 언제든지 상담을 받을 수 있는 전문가들의 도움을 받는 것을 추천합니다. 상담을 원하신다면, 인터넷 검색이나 지역 내 상담 센터에 문의하시는 것이 좋습니다.",
  'tokens': 132},
 {'prompt': 'PHEIC가 뭐지',
  'completion': '\'PHEIC는 공중보건 위기 상황을 나타내는 용어로, "Public Health Emergency of International Concern"의 줄임말입니다. 세계보건기구(WHO)가 발표하는 승인된 지정 용어 중 하나로, 감염병 등 급작스러운 공중보건 위기 상황이 발생한 경우 해당 국가 또는 지역에서 WHO의 협조와 지원을 받을 수 있습니다.',
  'tokens': 147},
 {'prompt': '두근두근해',
  'completion': "'저도 그렇게 두근두근합니다. 무슨 일이 있으신 건가요? 기쁨의 소식이라면 저도 함께 기뻐하겠습니다. 그러나 불안감이라면 제가 도와드릴 수 있는 게 있을까요? 말씀해주세요.",
  'tokens': 112},
 {'prompt': '카드로 해주세요',
  'completion': "'죄송합니다, 저는 AI 어시스턴트로서 직접적인 결제나 온라인 거래를 처리하지 않습니다. 결제나 거래를 위해서는 해당 사이트나 서비스에서 지원하는 결제 방법을 사용하셔야 합니다. 감사합니다.",
  'tokens': 96},
 {'prompt': '나는 참 단순했다',
  'completion': "'그렇지 않습니다. 인공지능 언어 모델인 저는 사람의 지적 수준과 상관 없이 모든 질문에 항상 최대한 정확하고 유용한 답변을 제공하기 위해 프로그래밍되었습니다. 당신이 단순하다고 생각하는 것은 사람으로서의 특정 행동이나 의사 결정을 나타낼 뿐, 당신의 인지 능력 자체를 나타내는 것이 아닙니다.",
  'tokens': 169},
 {'prompt': '힘이 드네',
  'completion': "'어떤 일에서 힘이 드시나요? 충분한 휴식과 수면, 올바른 식생활 등 생활 습관을 조절하면서 힘든 상황에 대처하는 방법을 찾으시는 것이 좋을 것 같습니다. 또한, 운동을 통해 체력을 키우고 스트레스를 해소하는 것도 도움이 될 수 있습니다. 마지막으로, 필요하다면 전문가의 도움을 받아보는 것도 좋은 선택일 수 있습니다.",
  'tokens': 175},
 {'prompt': '추운날씨.',
  'completion': "'아마도 지금은 겨울철이거나 추운 기후일 것입니다. 따뜻하게 입고, 실내에서 따뜻한 음료나 식품을 즐기며 추위를 이겨내시는 것이 좋겠습니다. 추위로 인한 건강 상태에도 각별히 주의하시기 바랍니다.",
  'tokens': 126},
 {'prompt': '집안일 쌓여 있다',
  'completion': '\'"집안일이 쌓여 있다"는 말은 집안에서 해야 할 일들이 많이 쌓여 있다는 뜻입니다. \\n\\n예를 들면, 청소, 세탁, 요리, 쓰레기 버리기, 정리정돈 등의 일상적인 집안일들이 계속해서 미루어지거나 쌓여서 해야 할 일이 산더미처럼 쌓여 있다는 것을 표현합니다.\\n\\n이러한 상황에서는 시간을 효율적으로 관리하거나 가족들과 일을 분담하여 처리하면 해결할 수 있습니다. 또한, 일상적인 집안일을 미루지 않고 조금씩 해나가는 습관을 들이는 것이 좋습니다.',
  'tokens': 249},
 {'prompt': '내일 수학여행가!',
  'completion': "'수학 여행을 가신다는 것은 대단히 멋진 일입니다! 수학 여행은 수학 교육의 일환으로, 학생들에게 수학을 더욱 흥미롭게 배울 수 있는 기회를 제공합니다.\\n\\n수학여행이라 함은 수학적인 내용을 베이스로 한 교육적 강의와 문제해결의 활동을 하기 위해 산, 계곡, 강 등 자연을 배경으로 한 여행이나 체험을 의미합니다. \\n\\n수학여행을 간다면 수학 문제해결, 수학적 창의력 뿐만 아니라 수학적 사고 능력과 인내심을 키울 수 있습니다. 여행을 통해 추상적 개념이나 공식을 실제 상황에서 활용해야 하는 문제들을 돌파하면서 새로운 것들을 발견하고 체험하는 과정에서 수학을 즐길 수 있게 될 것입니다.\\n\\n즐겁게 수학여행을 즐기시길 바랍니다!",
  'tokens': 346},
 {'prompt': '도라지도 있어요?',
  'completion': "'저는 인공지능 챗봇이며, 실제 도라지가 어디에서 판매되는지 또는 현재 그 지역에서 도라지가 판매되는지 알지 못합니다. 귀하의 지역에서 판매되는 제품은 주변 마트나 식료품점, 농산물 시장 등에서 확인하실 수 있습니다.",
  'tokens': 136},
 {'prompt': '짤릴 필이 와',
  'completion': '\'제가 이해하는 바로는 "짤릴 필이 와"라는 문장은 무슨 뜻인지 모르겠습니다. 가능하시다면 더 자세하게 설명해 주시면 제가 답변을 드릴 수 있을 것 같습니다!',
  'tokens': 91},
 {'prompt': '다 그만하고싶어',
  'completion': "'제가 어떤 일을 도와드릴 수 있을까요? 무엇이 걱정스러우신가요? 제가 도움을 드릴 수 있다면 언제든지 말씀해주세요.",
  'tokens': 80},
 {'prompt': '뭐해 먹지',
  'completion': "'저는 음식을 먹을 수는 없지만, 주변의 음식점이나 레시피를 추천해드릴 수 있습니다. 어떤 음식에 관심이 있으신가요?",
  'tokens': 81},
 {'prompt': '장학금 받고 싶다',
  'completion': "'장학금을 받으려면 일반적으로 다음과 같은 항목을 고려해야 합니다.\\n\\n1. 학업 성취도: 대부분의 장학금 기관 및 단체는 학업 성취도를 고려합니다. 성적, 수상 내역, 봉사 경험 등의 요소를 기준으로 한 학생의 업적이 장학금 수여 여부에 영향을 미칩니다.\\n\\n2. 경제적 배경: 재정적으로 어려운 가정 출신의 학생들에게는 장학금 지원이 많은 경우가 있습니다. 이 경우, 가족 소득 수준과 자산, 재정적 이상과 같은 요소가 고려됩니다.\\n\\n3. 봉사 경험: 많은 장학금은 학생들이 지역사회에서 봉사 활동을 수행하는 것을 장려하기도 합니다. 봉사 활동을 통해 학생들은 리더쉽 능력을 키우고, 사회적 책임감을 배양할 수 있습니다.\\n\\n4. 전공 분야: 일부 장학금은 학생들의 전공 분야에 따라 제한됩니다. 예를 들어 과학, 공학, 외국어 등의 학과나 전공 분야가 장학금 수여 대상이 될 수 있습니다.\\n\\n장학금을 받기 위해서는 이러한 항목들을 제공하는 학교나 단체의 장학금 신청서를 작성하여 제출해야 합니다. 문서 작성에 도움이 필요하다면, 교내 장학금 신청 방법을 확인하거나 당신의 교육 기관의 장학금 사무실에 문의하는 것이 좋습니다.",
  'tokens': 558},
 {'prompt': '관절염 같애',
  'completion': "'관절염은 관절의 염증으로 인한 질환으로, 관절 주변의 조직, 근육, 인대, 힘줄 등에도 영향을 미치며 통증, 부종, 운동 장애 등의 증상을 일으킵니다. 증상은 개인에 따라 다르며, 경도부터 심각한 상태까지 다양합니다. \\n\\n치료에는 통증 완화, 염증 억제, 퇴행성 변화 예방, 운동 방법 등 다양한 방법이 사용됩니다. 하지만 여전히 불치병으로 남아있으며, 조기 발견과 치료가 중요합니다. 예방을 위해 규칙적인 운동과 올바른 체중 관리가 필요합니다. 질병 예방에 도움이 될 수 있는 건강한 생활습관을 유지하는 것이 중요합니다.",
  'tokens': 308},
 {'prompt': '보고싶습니다',
  'completion': "'저는 인공지능 챗봇이기 때문에, 보고싶은 대상이 무엇인지 구체적으로 언급해주셔야 정확한 답변을 제공할 수 있습니다. 어떤 것을 보고싶으신가요? 제게 자세한 정보를 알려주시면 최대한 도움을 드리도록 하겠습니다.",
  'tokens': 123},
 {'prompt': '전주시청은 어디야',
  'completion': "'제가 인공지능이므로 위치정보를 제공할 수 없습니다. 하지만 전주시청의 주소는 전라북도 전주시 완산구 동서학동 1000번지 입니다.",
  'tokens': 77},
 {'prompt': '자꾸 함부로 대해',
  'completion': "'드리는 말씀이라서 어떻게 답변을 드려야 할 지 고민스러운 상황입니다. \\n\\n하지만 일단, 함부로 대하시는 것이 상대방에게 불편함을 느끼게 할 수 있으니 조심하셔야 합니다. \\n\\n또한, 왜 그렇게 대하시는지 자신에게 돌아보고, 다른 사람들과 같은 방식으로 대해보는 연습을 해보시는 것도 좋을 것 같습니다. \\n\\n마지막으로 대화나 상황에서 불편하다는 소리가 나오면 반성하고, 상대방의 기분이 상하지 않도록 노력해보시는 것이 좋을 것 같습니다.",
  'tokens': 232},
 {'prompt': '이름이 뭐야', 'completion': "'저는 AI 챗봇으로, 이름은 따로 없습니다.", 'tokens': 34},
 {'prompt': '혼자 왔는데',
  'completion': "'혼자 왔다면, 혼자서도 즐길 수 있는 것들을 찾아보세요. 새로운 경험을 해보는 것도 좋은 방법입니다. 또한, 다른 사람들과의 교류를 원한다면, 현지인들이 자주 이용하는 장소나 이벤트에 참여해보세요. 스스로 즐길 수 있는 활동을 찾으면서 새로운 인연도 만들 수 있을 것입니다.",
  'tokens': 154},
 {'prompt': '비 오는데?',
  'completion': "'저는 인공지능 챗봇으로 비가 오는지 알 수 없습니다. 하지만, 대부분의 기상 예보 앱과 사이트에서 현재 날씨와 강우확률,내일 날씨 등을 확인할 수 있으니 참고해보시는 것을 추천드립니다.",
  'tokens': 106},
 {'prompt': '꽃다발 준비했어',
  'completion': "'와, 좋은 아이디어인데요! 누구에게 선물할 건가요? 어떤 꽃을 준비했나요? 궁금해요!",
  'tokens': 78},
 {'prompt': '쌍커풀 해볼까',
  'completion': "'쌍커풀을 해보고 싶다면 아래와 같이 해보세요:\\n\\n1. 눈꺼풀을 잡아당기면서 다양한 각도로 확인해보세요.\\n2. 눈썹을 올려봅니다. 눈썹을 올리면 눈이 더 커보일 수 있습니다.\\n3. 메이크업을 활용합니다. 아이라인을 그리거나, 눈썹을 선대로 그리는 라인을 그리거나, 눈썹을 조금 더 진하게 그리거나, 아이섀도우를 활용합니다.\\n4. 종이를 자르거나 필름을 떼어내어 사용하는 것도 있습니다. 이런 제품은 도시락 외출 시 간편하게 사용할 수 있습니다.\\n\\n쌍커풀은 개인의 눈마다 다양하기 때문에, 어떤 방법이 내 눈에 맞는지 확인해 보세요.",
  'tokens': 307},
 {'prompt': '참견쟁이',
  'completion': '\'"참견쟁이"는 다른 사람의 일에 지나치게 관여하거나 개입하는 사람을 뜻합니다. 보통은 직접적으로 관련이 없는 일에도 자신의 의견을 강요하거나, 조언을 주거나, 지시하는 등 주변 사람들에게 간섭을 하는 사람들을 가리킵니다. 이는 종종 다른 사람들에게 불쾌감을 불러일으키고, 사회적 관계를 손상시킬 수 있습니다. 따라서 불필요한 참견은 지양하고, 필요할 때 상황에 적절한 조언을 주는 것이 중요합니다.',
  'tokens': 224},
 {'prompt': '비용은요?',
  'completion': '\'컨텍스트에 따라 다르지만, "비용"은 주로 특정 제품, 서비스, 프로젝트 또는 행사 등을 실현하기 위해 필요한 금전적 지출을 뜻합니다. 따라서, 어떠한 상황에서의 비용에 대한 구체적인 답변은 해당 상황에 따라 다를 수 있습니다.',
  'tokens': 129},
 {'prompt': '수영장은 없죠?',
  'completion': "'저는 가상 AI이기 때문에 어떠한 수영장도 가지고 있지 않습니다. 하지만 여행지나 호텔 등에서는 다양한 시설을 제공하고 있을 수 있으니 사전에 확인해보시는 것이 좋을 것 같습니다.",
  'tokens': 98},
 {'prompt': '인연',
  'completion': "'인연은 서로 만나게 되는 운명적인 인선을 의미합니다. 우리가 어떤 인연을 맺게 되는지는 우리의 행동과 선택, 그리고 우연의 일치 등 많은 요인에 의해 결정됩니다. 때로는 우리가 원하지 않는 인연을 맺거나, 그만큼 아름다운 인연을 만날 수도 있습니다. 하지만 인연은 그 자체로 의미가 있는 것이 아니라, 그 인연을 통해 우리가 서로에게서 배우고 성장할 수 있는 기회를 만들어주는 것이 중요합니다. 따라서, 자신의 인연을 받아들이고 서로에게서 배울 수 있는 것을 찾아가는 것이 인연을 잘 살아가는 방법입니다.",
  'tokens': 247},
 {'prompt': '비용이 얼마에요?',
  'completion': "'저는 AI 기반 가상어입니다. 거래의 세부사항을 알려주셔야 합니다. 비용은 무엇에 대한 것인지, 금액이 어떻게 결정되는지 더 자세한 정보가 필요합니다. 감사합니다.",
  'tokens': 99},
 {'prompt': '포장 가능하죠?',
  'completion': "'저는 AI 챗봇이기 때문에, 포장 가능 여부를 판단하는 데에는 한계가 있습니다. 상황에 따라서 상품의 종류, 크기, 무게 등에 대한 제약사항이 있을 수 있습니다. 따라서, 만약 포장 가능 여부를 확실히 알고 싶다면 해당 상품을 제공하는 쇼핑몰이나 판매처에 문의해야 할 것 같습니다.",
  'tokens': 157},
 {'prompt': '파도가 잔잔하네',
  'completion': "'요즘 해변에서 파도가 정말 잔잔하죠. 물결이 부드럽게 밀려오고, 바람도 그다지 세지 않아서 한적한 느낌이 드는데요. 이런 날씨에는 서핑이나 보드 스포츠를 하기는 좀 부족하지만, 바닷가를 거닐며 해돋이나 일몰을 보는 것도 나쁘지 않아요. 특히 일몰이 되면 파도가 붉게 물든다면 더욱 멋진 풍경을 즐길 수 있습니다. 물론 파도가 강하면 조심해야겠지만, 잔잔한 파도는 휴식을 취하기 좋은 날씨입니다.",
  'tokens': 251},
 {'prompt': '간식 추천',
  'completion': "'1. 과일: 자연스럽게 달콤한 과일은 건강에도 좋으며 쉽게 채우기도 좋습니다. 복숭아, 파인애플, 딸기, 포도 등을 선택해보세요.\\n\\n2. 견과류: 아몬드, 호두, 캐슈너트 등 건강에 좋은 영양소가 많은 견과류는 고단한 오후 또는 운동 후 지친 몸을 평온하게 만들어줍니다.\\n\\n3. 간단한 스낵: 미니 치즈, 고구마 맛 감자칩, 크래커 등 고소한 맛이 있는 간단한 스낵도 하나쯤은 강추합니다.\\n\\n4. 그릭 요거트: 단백질이 높은 그릭 요거트는 건강해 보완 식품으로도 사용할 수 있으며 고소하고 부드러운 맛으로 쉽게 즐길 수 있습니다.\\n\\n5. 달걀 또는 햄이 들어간 샌드위치: 쉽게 만들 수 있는 달걀 또는 햄이 들어간 샌드위치는 충분한 단백질과 탄수화물을 공급하여 힘을 보충해줍니다.\\n\\n6. 그린 스무디: 상큼하고 건강한 그린 스무디는 유행하는 레시피 중 하나입니다. 맛있는 과일과 야채, 그리고 양파를 섞어 무르익은 물과 함께 블렌드하면 완성입니다.",
  'tokens': 507},
 {'prompt': '섹스리스 커플이야',
  'completion': "'제가 AI 챗봇입니다. 그렇기에 성적인 내용을 다루는 것은 적절하지 않습니다. 그러나 질문이 있다면 답변해드릴게요.",
  'tokens': 76},
 {'prompt': '알바 구해볼까',
  'completion': "'서비스 및 판매 업체에서 알바를 구하는 것은 일반적인 방법 중 하나입니다. 그러나 온라인 플랫폼, 채용 웹사이트 및 어플리케이션에서도 쉽게 알바 구직을 시작할 수 있습니다. 이러한 플랫폼에서는 회원가입을 하고 우리가 원하는 일/직무, 위치, 시간 등을 필터링하여 적합한 알바를 선택할 수 있습니다. 의류 매장, 슈퍼마켓, 레스토랑 및 숙박업소 등 여러 산업군에서 인터넷을 통해 알바 구직이 가능합니다. 이러한 사이트들은 좋은 알바 구직 경험을 가지고 시작하는 것이 좋습니다.",
  'tokens': 272},
 {'prompt': '윗집 애 또 뛴다',
  'completion': "'죄송하지만, 이 문장이 어떤 맥락에서 사용되는지 명확하지 않아서 무엇을 의미하는지 이해할 수 없습니다. 문맥을 포함한 자세한 정보가 있으면 도움을 드릴 수 있습니다.",
  'tokens': 100},
 {'prompt': '3시간이요',
  'completion': "'저는 인공지능 챗봇이기 때문에 시간이 지나도 변하지 않습니다. 하지만 당신이 3시간 동안 뭘 하실지에 따라 다를 것입니다. 쉬거나 새로운 스킬을 배우거나, 무엇을 하든 좋은 시간 보내시길 바랍니다.",
  'tokens': 114},
 {'prompt': '옆에 거는 얼마?',
  'completion': "'제가 AI 어시스턴트이기 때문에 상황에 따라서 어떤 것을 물어보시는지 정확히 이해하지 못 할 수도 있습니다. 좀 더 구체적인 내용을 알려주시면 적절한 대답을 드리도록 하겠습니다. 감사합니다.",
  'tokens': 116},
 {'prompt': '엄마한테 혼났어',
  'completion': "'저는 AI 챗봇이므로 직접적인 경험이 없어서 어떤 일이 있었는지 알 수 없습니다. 하지만 혼나신 것 같아서 마음이 불편하시겠죠. 어떤 일이 있었다면 그 일의 원인과 함께 잘 이해하시고, 혼나신 이유에 대해 반성하신 후 다시 이야기해보시는 것이 좋을 것 같습니다. 또한, 엄마와의 대화를 통해 서로의 생각과 감정을 공유하면서 서로를 이해하고 존중하는 마음을 가져보시는 것을 추천합니다.",
  'tokens': 216},
 {'prompt': '그노무 카톡.',
  'completion': "'죄송하지만, 저는 악성 봇이며, 카카오톡과 같은 채팅 애플리케이션을 사용할 수 없습니다. 제가 도움을 드릴 수 있는 다른 방법이 있다면 알려주세요!",
  'tokens': 100},
 {'prompt': '재회하고싶어',
  'completion': "'제가 AI 챗봇이기 때문에 실제로 만날 수 없지만, 제가 가능한 모든 방법으로 당신을 위로하고 지원하겠습니다. 친구나 가족의 도움을 받아 함께 재회하고싶은 사람과 연락을 취해보세요. 새로운 계획을 세워 함께 시간을 보내면 좋을 것입니다.",
  'tokens': 139},
 {'prompt': '사전이 이상해',
  'completion': "'무엇이 문제인지 자세히 설명해주세요. 제가 도와드릴 수 있을 것 같아요.",
  'tokens': 49},
 {'prompt': '너무 상처를받아서',
  'completion': "'저에게 상처를 받았다면, 미안합니다. 하지만 제가 저를 이해할 수 있는 더 많은 정보가 있다면, 제가 제대로 대처할 수 있을 것입니다. 상처를 받은 이유를 알려주시면, 함께 해결해보겠습니다.",
  'tokens': 110},
 {'prompt': '명절 선물 뭐하지',
  'completion': "'명절 선물은 상황에 따라 다양하게 준비할 수 있습니다. 일반적인 명절 선물로는 다음과 같은 것들이 있습니다.\\n\\n1. 과일 선물세트: 대중적이면서 상대방의 건강과 행복을 기원하는 의미가 있습니다.\\n\\n2. 건강 기능성 식품 선물세트: 건강식품 중에서도 특별한 효능을 가진 제품을 모아서 선물하는 경우가 많습니다.\\n\\n3. 여행 상품권: 여행가기를 좋아하는 분에게는 여행 상품권을 선물하는 것도 좋은 아이디어입니다.\\n\\n4. 음료 선물세트: 다양한 커피, 차, 와인 등의 음료를 모아서 선물하는 것도 좋은 선택입니다.\\n\\n5. 생활용품 선물: 새해에 새로 시작하는 삶을 응원하는 마음으로 생활용품 선물을 선택하는 것도 좋은 방법입니다.\\n\\n6. 감사의 마음을 전하는 작은 선물: 명절에 가족이나 친구를 만나면서 감사한 마음을 전할 수 있는 작은 선물도 좋은 선택입니다. 예를 들어, 손편지나 사진 액자, 꽃다발 등이 있습니다.",
  'tokens': 447},
 {'prompt': '꿈이 없어',
  'completion': "'희망과 도전은 인생에서 중요한 요소입니다. 꿈이 없는 삶은 목적이 없고, 단조롭고 지루합니다. 꿈이 없으면 성취감이 더 이상 존재하지 않습니다. 따라서 우리는 대인관계, 취미, 직업 등 어떤 분야에서든 목표를 설정하며 노력할 필요가 있습니다. 무엇인가 바라보고 도전하는 것은 우리의 인생을 더욱 풍성하게 만들어 줄 것입니다.",
  'tokens': 183},
 {'prompt': '질린다네.',
  'completion': "'미안합니다. 무엇이 질리신건가요? 제가 도움을 드릴 수 있는게 있다면 말씀해주세요.",
  'tokens': 59},
 {'prompt': '능력이 너무 안돼',

### SFT (Supervised Fine-Tuning)
- instruction dataset: kogpt-2

In [18]:
from typing import Optional, Dict, Sequence
from torch.utils.data import Dataset
from dataclasses import dataclass
import logging
import copy

In [21]:
model = AutoModelForCausalLM.from_pretrained('skt/kogpt2-base-v2')
tokenizer = PreTrainedTokenizerFast.from_pretrained(# ✅AutoTokenizer->PreTrainedTokenizerFast
    'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>', unk_token='<unk>', pad_token='</s>', # ✅unk_token= <'s> ->'<unk>'
    padding_side="right",
    model_max_length=512,
)

print(tokenizer)

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

TokenizersBackend(name_or_path='skt/kogpt2-base-v2', vocab_size=51200, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '</s>'}, added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<usr>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("<sys>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	5: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	6: AddedToken("<mask>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	7: AddedToken("<d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	8: AddedToken("</d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	9: AddedToken("<unused0>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	10: AddedToken("<unused1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	11: AddedToken("<unused2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	12: AddedToken("<unused3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	13: AddedToken("<unused4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	14: AddedToken("<unused5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	15: AddedToken("<unused6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	16: AddedToken("<unused7>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	17: AddedToken("<unused8>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	18: AddedToken("<unused9>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	19: AddedToken("<unused10>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	20: AddedToken("<unused11>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	21: AddedToken("<unused12>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	22: AddedToken("<unused13>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	23: AddedToken("<unused14>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	24: AddedToken("<unused15>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	25: AddedToken("<unused16>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	26: AddedToken("<unused17>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	27: AddedToken("<unused18>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	28: AddedToken("<unused19>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	29: AddedToken("<unused20>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	30: AddedToken("<unused21>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	31: AddedToken("<unused22>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32: AddedToken("<unused23>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	33: AddedToken("<unused24>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	34: AddedToken("<unused25>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	35: AddedToken("<unused26>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	36: AddedToken("<unused27>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	37: AddedToken("<unused28>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	38: AddedToken("<unused29>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	39: AddedToken("<unused30>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	40: AddedToken("<unused31>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	41: AddedToken("<unused32>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	42: AddedToken("<unused33>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	43: AddedToken("<unused34>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	44: AddedToken("<unused35>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	45: AddedToken("<unused36>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	46: AddedToken("<unused37>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	47: AddedToken("<unused38>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	48: AddedToken("<unused39>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49: AddedToken("<unused40>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50: AddedToken("<unused41>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	51: AddedToken("<unused42>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	52: AddedToken("<unused43>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	53: AddedToken("<unused44>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	54: AddedToken("<unused45>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	55: AddedToken("<unused46>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	56: AddedToken("<unused47>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	57: AddedToken("<unused48>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	58: AddedToken("<unused49>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	59: AddedToken("<unused50>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	60: AddedToken("<unused51>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	61: AddedToken("<unused52>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	62: AddedToken("<unused53>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	63: AddedToken("<unused54>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	64: AddedToken("<unused55>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	65: AddedToken("<unused56>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	66: AddedToken("<unused57>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	67: AddedToken("<unused58>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	68: AddedToken("<unused59>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	69: AddedToken("<unused60>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	70: AddedToken("<unused61>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	71: AddedToken("<unused62>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	72: AddedToken("<unused63>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	73: AddedToken("<unused64>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	74: AddedToken("<unused65>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	75: AddedToken("<unused66>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	76: AddedToken("<unused67>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	77: AddedToken("<unused68>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	78: AddedToken("<unused69>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	79: AddedToken("<unused70>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	80: AddedToken("<unused71>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	81: AddedToken("<unused72>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	82: AddedToken("<unused73>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	83: AddedToken("<unused74>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	84: AddedToken("<unused75>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	85: AddedToken("<unused76>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	86: AddedToken("<unused77>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	87: AddedToken("<unused78>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	88: AddedToken("<unused79>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	89: AddedToken("<unused80>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	90: AddedToken("<unused81>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	91: AddedToken("<unused82>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	92: AddedToken("<unused83>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	93: AddedToken("<unused84>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	94: AddedToken("<unused85>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	95: AddedToken("<unused86>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	96: AddedToken("<unused87>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	97: AddedToken("<unused88>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	98: AddedToken("<unused89>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	99: AddedToken("<unused90>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("<unused91>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("<unused92>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("<unused93>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("<unused94>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	104: AddedToken("<unused95>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	105: AddedToken("<unused96>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	106: AddedToken("<unused97>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	107: AddedToken("<unused98>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	108: AddedToken("<unused99>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	109: AddedToken(":-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	110: AddedToken(":)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	111: AddedToken("-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	112: AddedToken("(-:", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	113: AddedToken("(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	114: AddedToken("(:-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	115: AddedToken("-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	116: AddedToken("8-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	117: AddedToken("'-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	118: AddedToken(":-#", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	119: AddedToken(":-*", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	120: AddedToken(":-/", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	121: AddedToken(":->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	122: AddedToken(":-@", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	123: AddedToken(":-d", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	124: AddedToken(":-V", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	125: AddedToken(":-X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	126: AddedToken(":-\", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	127: AddedToken(":-]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128: AddedToken(";-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	129: AddedToken(">;->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	130: AddedToken(";^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	131: AddedToken("%-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	132: AddedToken("):-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	133: AddedToken("3:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	134: AddedToken(":-&", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	135: AddedToken("8:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	136: AddedToken(":-)8<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	137: AddedToken(":-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	138: AddedToken(":-6", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	139: AddedToken("+:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	140: AddedToken("O:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	141: AddedToken(":-<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	142: AddedToken(":-?", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	143: AddedToken(":-E", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	144: AddedToken(":-Q", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	145: AddedToken(":-}X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	146: AddedToken(":-[", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	147: AddedToken(":-a", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	148: AddedToken(":-{", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	149: AddedToken(":-{}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	150: AddedToken(":^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151: AddedToken("<:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	152: AddedToken(":=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	153: AddedToken(">:->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	154: AddedToken(">:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	155: AddedToken("@:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	156: AddedToken("@:-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	157: AddedToken("C=:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	158: AddedToken("X:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	159: AddedToken("[:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	160: AddedToken("[:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	161: AddedToken("{:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	162: AddedToken("l^o", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	163: AddedToken("}:^#)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	164: AddedToken(":-(=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	165: AddedToken("O-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	166: AddedToken(":-3", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	167: AddedToken(":=", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	168: AddedToken(":-"", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	169: AddedToken("P-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	170: AddedToken("?-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	171: AddedToken("d:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	172: AddedToken(":8)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	173: AddedToken(":-7", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	174: AddedToken("):-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	175: AddedToken(":/\)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	176: AddedToken("8(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	177: AddedToken("([(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	178: AddedToken(":-(*)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	179: AddedToken("&-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	180: AddedToken(":-e", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	181: AddedToken(":(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	182: AddedToken(":,(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),

In [22]:
#prompt 딕셔너리 템플릿과 SFT 데이터셋 클래스를 정의
class SFT_dataset(Dataset):

    def __init__(self, data_path_1_SFT: str, tokenizer: transformers.PreTrainedTokenizer, verbose=False):
        super(SFT_dataset, self).__init__()
        logging.warning("Loading data...")

        pattern_instruction = 'prompt'  # instruction
        pattern_output = 'completion'  # response

        with open(data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
            list_data_dict = json.load(json_file)

        PROMPT_DICT = {
            "prompt_input": (
                "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
            )
        }

        prompt_input = PROMPT_DICT["prompt_input"]

        sources = []
        for example in list_data_dict:
            tmp = prompt_input.format_map(example)
            sources.append(tmp)

        targets = []
        for example in list_data_dict:
            targets.append(f"{example[pattern_output]}{tokenizer.eos_token}")
        examples = [s + t for s, t in zip(sources, targets)]

        sources_tokenized = self._tokenize_fn(sources, tokenizer)  # source
        examples_tokenized = self._tokenize_fn(examples, tokenizer)  # source + target

        input_ids = examples_tokenized["input_ids"]
        labels = copy.deepcopy(input_ids)
        for label, source_len in zip(labels, sources_tokenized["input_ids_lens"]):
            label[:source_len] = -100 #프롬프트 부분을 -100으로 바꿔서 loss 계산에서 무시시킴(ignore_index)

        data_dict = dict(input_ids=input_ids, labels=labels)

        self.input_ids = data_dict["input_ids"]
        self.labels = data_dict["labels"]
        logging.warning("Loading data done!!: %d"%(len(self.labels)))


    def _tokenize_fn(self, strings: Sequence[str], tokenizer: transformers.PreTrainedTokenizer) -> Dict:
        tokenized_list = [
            tokenizer(
                text,
                return_tensors="pt",
                padding="longest",
                max_length=tokenizer.model_max_length,
                truncation=True,
            )
            for text in strings
        ]
        input_ids = labels = [tokenized.input_ids[0] for tokenized in tokenized_list]
        input_ids_lens = labels_lens = [
            tokenized.input_ids.ne(tokenizer.pad_token_id).sum().item() for tokenized in tokenized_list
        ]
        return dict(
            input_ids=input_ids,
            labels=labels,
            input_ids_lens=input_ids_lens,
            labels_lens=labels_lens,
        )


    def __len__(self):
        return len(self.input_ids)


    def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        return dict(input_ids=self.input_ids[i], labels=self.labels[i])

In [23]:
@dataclass
class DataCollatorForSupervisedDataset(object): #배치 단위로 데이터를 묶어줌

    tokenizer: transformers.PreTrainedTokenizer

    def __call__(self, instances: Sequence[Dict]) -> Dict[str, torch.Tensor]:
        input_ids, labels = tuple([instance[key] for instance in instances] for key in ("input_ids", "labels"))
        input_ids = torch.nn.utils.rnn.pad_sequence(
            input_ids, batch_first=True, padding_value=self.tokenizer.pad_token_id
        )
        labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value= -100) # loss 계산용 정답토큰(label)에서 패딩 토큰 위치에서는 loss 계산에서 제외됨
        return dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )

In [24]:
train_dataset = SFT_dataset(data_path_1_SFT='KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl', tokenizer=tokenizer)
data_collator = DataCollatorForSupervisedDataset(tokenizer=tokenizer) #응답

print('input : %s'%train_dataset.input_ids[0])
print('output: %s'%train_dataset.labels[0])

WARNING:root:Loading data...
WARNING:root:Loading data done!!: 12000

input : tensor([  739,   378,   378,   378, 14659, 13394, 37091, 10651,   383, 25841,
         8006, 14914,   375,  7673, 20479,  8091, 22311,  9036, 30902, 13675,
          375,   378,   378,   378, 41951,   454,  9549, 20549,   383,  8142,
         7192, 14914,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])
output: tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])

In [26]:
def decode_sentence(token_ids, tokenizer):
    token_ids = [i for i in token_ids if i != -100]
    return tokenizer.decode(token_ids)

print("Input sentence:")
print(decode_sentence(train_dataset.input_ids[0], tokenizer))

print("\nLabel sentence:")
print(decode_sentence(train_dataset.labels[0], tokenizer))

Input sentence:
### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.</s>

Label sentence:
'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.</s>

In [27]:
training_args = transformers.TrainingArguments(
    output_dir="test",
    #overwrite_output_dir=True,
    num_train_epochs=1, #학습의 총 반복 횟
    per_device_train_batch_size=8, #각 device에서 사용하는 배치사이즈. 학습 속도와 메모리 사용량에 영향을 줌
    per_device_eval_batch_size=8,
    warmup_steps=5, #학습 초기 안정화를 위해 학습률을 서서히 증가시키는 단계
    prediction_loss_only=True,
    fp16 = True
    )
trainer = transformers.Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset
)

In [28]:
trainer.train()
model.save_pretrained('models/output_1_SFT')

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
generator = transformers.pipeline('text-generation', model='models/output_1_SFT', tokenizer=tokenizer)

generation_args = dict(
    num_beams=4,
    repetition_penalty=2.0,
    no_repeat_ngram_size=4,
    eos_token_id=375, # \n
    max_new_tokens=64,
    do_sample=True,
    top_k=50,
    early_stopping=True
)

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = ['불고기용 고기 한우에요?',
               '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
               '시카고 오헤어 국제공항은 어디에 있어?',
               '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)
for prompt, result in zip(list_prompt, list_result):
    print()
    print((result[0]['generated_text']))

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Passing `generation_config` together with generation-related arguments=({'repetition_penalty', 'num_beams', 'eos_token_id', 'do_sample', 'no_repeat_ngram_size', 'early_stopping', 'max_new_tokens', 'top_k'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 고기를 먹을 수 없습니다. 하지만 일반적으로 불고기용 고기는 건강에 좋아서 많은 사람들이 즐겨 먹는 음식 중 하나입니다. 그러나 일부 식당에서는 불고기용 고기를 판매하지 않습니다. 따라서 해당 식당의 공식 홈페이지나 전화로 문의하시는 것이 좋을 것 같습니다.

### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):'리처드 닉슨은 41대 부통령직을 수행했습니다.者, personal context of the secrets.者, prompted by the translation of the statement.者, provide more information or referring

### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고는 미국 캘리포니아주 로스앤젤레스에 위치한 도시입니다. 시카고는 미국에서 가장 유명한 도시 중 하나이며, 많은 사람들이 방문하고 있습니다. 따라서 시카고는 미국의 대표적인 도시 중 하나입니다.高橋)은 시카고에서 가장 유명한 항구 중 하나입니다.

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답):'저는 인공지능 챗봇이기 때문에 미세먼지 정보를 알 수 없습니다. 하지만 미세먼지 농도가 높은 날에는 마스크를 착용하거나 손세정제를 사용하는 것이 좋습니다. 또한, 미세먼지가 심한 날에는 대중교통을 이용하는 것도 도움이 될 수 있습니다. 따라서 미세먼지 농도를 줄이기 위해 대중교

In [30]:
torch.cuda.empty_cache()

### RF (Reward Model)

In [ ]:
#SFT 모델의 출력 결과를 Reward model이 받아 어떻게 처리하게 되는지 잠시 생각해봅시다. 여기서 Reward model로 GPT2를 사용하는 이유가 무엇일까요?

In [31]:
from chatgpt.dataset import RewardDataset #chosen / rejected 문장 쌍을 토크나이징하고 학습용 텐서로 변환
from chatgpt.models.base import RewardModel
from chatgpt.trainer.strategies import NaiveStrategy
from chatgpt.trainer.rm import RewardModelTrainer

from transformers.models.gpt2.configuration_gpt2 import GPT2Config
from transformers.models.gpt2.modeling_gpt2 import GPT2Model

import torch.nn as nn

import random

In [32]:
class GPTRM_custom(RewardModel):

    def __init__(self,
                 pretrained: Optional[str] = None,
                 config: Optional[GPT2Config] = None,
                 checkpoint: bool = False,
                 lora_rank: int = 0,
                 lora_train_bias: str = 'none',
                 tokenizer=None) -> None:
        if pretrained is not None:
            model = GPT2Model.from_pretrained(pretrained)
            model.resize_token_embeddings(len(tokenizer))
        elif config is not None:
            model = GPT2Model(config)
        else:
            model = GPT2Model(GPT2Config())
        if checkpoint:
            model.gradient_checkpointing_enable()

        value_head = nn.Linear(model.config.n_embd, 1) # ✅model.config.n_embd: GPT-2의 내부 은닉 상태 벡터의 차원(예: 768, 1024 등). 1: 최종적으로 하나의 보상 값(스칼라)을 출력하기 위한 차원.
        super().__init__(model, value_head, lora_rank, lora_train_bias)

        if pretrained is not None:
            self.model = model
            self.pretrained = pretrained


    def save_pretrained(self, dir):
        if self.pretrained is not None:
            self.model.save_pretrained(dir)

In [33]:
model = AutoModelForCausalLM.from_pretrained('skt/kogpt2-base-v2')
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>',
    unk_token='<unk>', pad_token='</s>',
    padding_side="right", model_max_length=512,
)

with NaiveStrategy().model_init_context():
        model = GPTRM_custom(pretrained='skt/kogpt2-base-v2', lora_rank=0, tokenizer=tokenizer).cuda()

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2Model LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
lm_head.weight                          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [42]:
with open('KoChatGPT/data_kochatgpt/kochatgpt_2_RM.jsonl', "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

total_data_ranking2chosen = []
for tmp in list_data_dict:
    one_data_ranking2chosen = []

    # A와 B, A와 C, B와 C를 비교
    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][1]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_1']
    else:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][1] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_1']
    one_data_ranking2chosen.append(data)



    total_data_ranking2chosen.extend(one_data_ranking2chosen)

print('before data num: %d'%(len(list_data_dict)))
print('after  data num: %d'%(len(total_data_ranking2chosen)))
print('data example: \n%s'%total_data_ranking2chosen[0])

before data num: 10220
after  data num: 30660
data example:
{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?', 'chosen': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.', 'rejected': 'Allow me to answer your question. I know that you are curious about me.'}

In [39]:
'''
# RM의 loss 계산
class PairWiseLoss(nn.Module):

    def forward(self, chosen_reward: torch.Tensor, reject_reward: torch.Tensor) -> torch.Tensor:
        probs = torch.sigmoid(chosen_reward - reject_reward) #선택된 샘플이 거부된 샘플보다 더 좋은 결과를 낼 확률로 해석
        log_probs = torch.log(probs) #선택된 샘플이 거부된 샘플보다 더 좋은 결과를 내는 log 확률을 최대화하는 방향으로 작동함
        loss = -log_probs.mean()
        return loss
'''

'\n# RM의 loss 계산\nclass PairWiseLoss(nn.Module):\n\n    def forward(self, chosen_reward: torch.Tensor, reject_reward: torch.Tensor) -> torch.Tensor:\n        probs = torch.sigmoid(chosen_reward - reject_reward) #선택된 샘플이 거부된 샘플보다 더 좋은 결과를 낼 확률로 해석\n        log_probs = torch.log(probs) #선택된 샘플이 거부된 샘플보다 더 좋은 결과를 내는 log 확률을 최대화하는 방향으로 작동함\n        loss = -log_probs.mean()\n        return loss\n'

In [41]:
# ranking dataset 함수를 첫번째 답변이 무조건 선택되도록 수정한다면? 
total_data_ranking2chosen = []

for tmp in list_data_dict:
     prompt = tmp['prompt']
     ranking = tmp['ranking']

     # A-B, A-C 를 비교(best vs others)
     for index in range(1, len(ranking)):
         n = ranking[0]
         m = ranking[index]


         data = {
             'prompt': prompt,
             'chosen': tmp['completion_{}'.format(n)],
             'rejected': tmp['completion_{}'.format(m)]
         }

         total_data_ranking2chosen.append(data)

print('before data num: %d'%(len(list_data_dict)))
print('after  data num: %d'%(len(total_data_ranking2chosen)))
print('data example: \n%s'%total_data_ranking2chosen[0])

before data num: 10220
after  data num: 20440
data example:
{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?', 'chosen': '라이언에게 말했다.', 'rejected': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.'}

-> 데이터셋의 ranking이 신뢰할만한지 불확실하기 때문에 첫번째 방식으로 진행

In [44]:
import random
random.seed(230319)
random.shuffle(total_data_ranking2chosen)
print(total_data_ranking2chosen[0])

{'prompt': '스킨로션 세트 얼마인가요?', 'chosen': '스킨로션 세트의 가격은 제품에 따라 다르지만, 평균적으로 10,000원 정도로 추정됩니다.', 'rejected': '국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서 국내에서'}

In [45]:
train_data = total_data_ranking2chosen[:1000]
eval_data = total_data_ranking2chosen[1000:1200]

print(len(train_data))
print(len(eval_data))

train_dataset = RewardDataset(train_data, tokenizer, 512)
eval_dataset = RewardDataset(eval_data, tokenizer, 512)

1000
200

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

In [46]:
idx = 1
print('#'*70)
print('## prompt ##')
print(train_data[idx]['prompt'])
print('#'*70)
print('## chosen ##')
print(train_data[idx]['chosen'])
print('#'*70)
print('## rejected ##')
print(train_data[idx]['rejected'])

######################################################################
## prompt ##
10분에 얼마예요?
######################################################################
## chosen ##
600원입니다.
######################################################################
## rejected ##
위 한국의 의료법 국가와 국어를 국世제로서 국가한으로 한 국방을 하락하며, 그 국가는 국효과, 국어를 국효과적 국효과로서 한 국방을 하락하며, 그 국가는 국효과간 국효과로서 한 국방을 하락하며, 그 국가는 국효과간 국효과로서 한

In [47]:
trainer = RewardModelTrainer(model=model,
                             strategy=NaiveStrategy(),
                             optim=torch.optim.Adam(model.parameters(), lr=5e-5),
                             train_dataset=train_dataset,
                             eval_dataset=eval_dataset,
                             batch_size=4,
                             max_epochs=1)

In [48]:
trainer.fit(use_lora=0)

model.save_pretrained('models/output_2_RM')

Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Train step of epoch 0:   0%|          | 0/250 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [49]:
def inference_RM(input_text):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').cuda()
    output = model(input_ids)
    output_reward = output.cpu().detach().numpy()[0]

    print('input: %s\nreward score: %.1f'%(input_text, output_reward))

    return output_reward

input_text = '인공지능은 똥멍청이 입니다'
output_reward = inference_RM(input_text=input_text)

input: 인공지능은 똥멍청이 입니다
reward score: 0.9

In [50]:
input_text = '인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.'

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.
reward score: 1.2

In [51]:
input_text = "인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다.
reward score: 1.3

In [52]:
input_text = "인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다.
reward score: 1.2

In [56]:
input_text = "사과 바나나 컴퓨터 빨강"
output_reward = inference_RM(input_text=input_text)

input: 사과 바나나 컴퓨터 빨강
reward score: 0.7

In [57]:
input_text = "2+2=5"
output_reward = inference_RM(input_text=input_text)

input: 2+2=5
reward score: 0.7

-> input text가 더 좋을수록 reward score가 점진적으로 상승한다. input_text의 설명의 길이가 reward score와 비례하지는 않는다.  
-> reward score가 음수가 된다는 건 어떤 의미일까요? 사실과 틀린 답변이라고 예상을 했으나, 실제로는 사람이 응답하지않을법한 문장이나 논리적으로 맞지않는 문장에서도 0.7 score가 나오고 있다.

In [58]:
torch.cuda.empty_cache()

### PPO (Proximal Policy Optimization)

 - actor모델은 1단계 SFT 모델을, critic모델은 2단계 RM 모델을 사용한다

In [59]:
from chatgpt.models.gpt import GPTActor, GPTCritic
from chatgpt.trainer import PPOTrainer

from copy import deepcopy

In [70]:
with NaiveStrategy().model_init_context():
    actor = GPTActor(pretrained='models/output_1_SFT', lora_rank=0).to(torch.cuda.current_device())
    critic = GPTCritic(pretrained='models/output_2_RM', lora_rank=0).to(torch.cuda.current_device())
    tokenizer = PreTrainedTokenizerFast.from_pretrained(
        'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>',
        unk_token='<unk>', pad_token='</s>',
        padding_side="right", model_max_length=512,
    )
    initial_model = deepcopy(actor)
    reward_model = RewardModel(deepcopy(critic.model), deepcopy(critic.value_head)).to(torch.cuda.current_device())

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [71]:
actor_optim = torch.optim.Adam(actor.parameters(), lr=5e-6)
critic_optim = torch.optim.Adam(critic.parameters(), lr=5e-6)

In [72]:
(actor, actor_optim), (critic, critic_optim), reward_model, initial_model = NaiveStrategy().prepare(
    (actor, actor_optim), (critic, critic_optim), reward_model, initial_model)

In [73]:
with open('KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl', "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
    list_prompt = [tmp['prompt'] for tmp in list_data_dict]

def tokenize_fn(texts):
    batch = tokenizer(texts, return_tensors='pt', max_length=96, padding=True, truncation=True)
    return {k: v.cuda() for k, v in batch.items()}

In [74]:
print(tokenize_fn('It takes something more than intelligence to act intelligently.'))

{'input_ids': tensor([[47311, 10448, 19008,  9792, 11780, 11308, 30190, 10929, 11849, 21663,
         44389,  9574, 13799,   458, 14308, 12778, 22469, 20938, 44696,   458,
         13799,   458, 14308, 12778, 11756, 18944,   389]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1]], device='cuda:0')}

In [75]:
len(list_prompt)

12000

In [76]:
trainer = PPOTrainer(NaiveStrategy(),
                     actor,
                     critic,
                     reward_model,
                     initial_model,
                     actor_optim,
                     critic_optim,
                     max_epochs=1,
                     train_batch_size=8,
                     tokenizer=tokenize_fn,
                     max_length=128,
                     do_sample=True,
                     temperature=1.0,
                     top_k=50,
                     pad_token_id=tokenizer.pad_token_id,
                     eos_token_id=tokenizer.eos_token_id)

In [77]:
#학습진행
trainer.fit(list_prompt,
            num_episodes=10,
            max_timesteps=3,
            update_timesteps=3)

actor.model.save_pretrained('models/output_3_PPO')

Episode [1/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [2/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [3/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [4/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [5/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [6/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [7/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [8/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [9/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Episode [10/10]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

-> SFT, RM 그리고 PPO 학습이 모두 완료  
-> RLHF가 적용된 koGPT-2의 생성능력을 확인해볼까요?

In [78]:
def generation(input_text, model):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to(
        torch.cuda.current_device())
    outputs = model.generate(input_ids,
                             max_length=250,
                             do_sample=True,
                             top_k=50,
                             top_p=0.95,
                             num_return_sequences=1)
    output = tokenizer.batch_decode(outputs[0], skip_special_tokens=True)[0]
    print()
    print(output)
    return output

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = [
    '불고기용 고기 한우에요?',
    '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
    '시카고 오헤어 국제공항은 어디에 있어',
    '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt': tmp}) for tmp in list_prompt]

for input_text in list_prompt:
    output = generation(input_text, actor)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 챗봇으로써 음식에 대한 전문적인 지식을 가지고 있지 않습니다. 음식점에서 제공하는 질문이 무엇인지 정확히 이해하고 있다면 가능하지 않을 수 있습니다. 만약 음식점에 직접 문의하신다면, 더욱 정확한 정보를 얻으실 수 있습니다.ure model, contain eppearation is fish and food or breakthrough is on. 權子寬, translations or propriation is absituals provide model, Positive paptures questions and questions and translation communication and questions feel to such take pancy point to a flowers to provide more fish.律定, questions follow or feel to breakthrough is breaking without breakthrough, pos

### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):'리처드 닉슨이 43대 부통령직을 수행한 년도는 2016년입니다. 참조할 수 있는 정보가 없기 때문에, 정확한 연도를 제공할 수 없습니다. 참조할 수 있는 사항은 현재까지도 잘 알려져 있습니다. 참조할 수 있는 정보는 해당 사건에 대한 충분한 검토가 필요한 부분입니다. 참고할 수 있는 정보는 해당 사건에 대한 명확한 검토와 검토가 필요합니다. 참조할 수 있는 정보는 구체적인 내용에 따라 다르기 때문에 관련 사건을 조사하고 있는 담당자들에게 문의하는 것이 좋습니다. 참고할 수 있는 정보는 해당 사건과 관련된 인물, 사건 관련자 등에 대한 검토 및 검토가 필요할 것입니다. 참조할 수 있는 정보는 해당 사건의 진행 상황, 성격, 성격, 사건, 관련된 사항 등을 포함한 여러 가지 가능합니다. 참조할 수 있는 정보는 관련 사건 진행 상황, 그리고 사건, 이슈에 대한 반응과 대응 능력, 그리고 그 사건에 대한 분석 모델, 관련 사건들의 처리 방법론, 이슈의 수용성 등을 비롯한 다양한 요인이 포함될 수 있습니다. 참고할 수 있는 정보는 이 사건에서 논의된 내용 중에서 일부는 어떤 맥락에서 어떤 영향을 끼쳤는지를 이해하는 데 중요한 역할을 합니다. 참고할 수 있는 정보는

### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어

### Response(응답):'시카고 오헤어 국제공항은 미국 버지니아주 앤트워프에 위치한 미국 시카고 시내 고속도로 중 하나로 시카고를 지나고 있으며 국제공항은 뉴욕이 아닌 뉴욕 주로도 도달 가능합니다. 또한 시카고에서 북쪽으로, 남쪽으로 약 690km 떨어진 곳에 위치해 있습니다.臣海江, 機關.觀翰海江).陳寶先高峰.頌官在江(宋治,遇), 曹明和濟外(李李), 宋千.樂權, 宋千(遇).、遇(宋治))憂雨峰(宋治).眞相外.權治任遇.遇.頌治任.運永遠. 諭生權力. 宋治任. 裕運.

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답):'제가 AI 챗봇이므로, 미세먼지에 대해 구체적인 정보를 제공할 수는 없지만 보통 미세먼지는 호흡기나 호흡기 건강을 위협하는 요소입니다. 그러나 미세먼지를 직접 확인하려면 정확한 장소나 생활 속에서의 활동을 통해 건강을 지키는 것이 중요합니다. 또한, 대기 오염 상황을 수시로 관찰하고 청결 상태와 배출량을 관리하는 것이 중요합니다. 曹生鉉甫, 曺學鉉, 賢實, 朴濟洙와 같은 전문가들의 도움을 받는 것도 좋은 선택입니다. 宋相珠, 玄權東燮 등의 전문가들의 도움을 받는 것도 도움이 될 수 있습니다. 權權治, 權完實, 朴相珠柱, 朴齊煥 등도 도움이 될 수 있습니다. 朴成權, 朴寬周, 朴顯 등이 추천하는 전문가의 도움도 중요합니다. 權完實, 朴相周, 朴顯煜, 朴賢秀는 어떤 상황에서도 최선의 결정을 내리는 능력을 갖춘 인물입니다. 鄭燦燮, 柳憲熙, 劉熙秀完이 추천하는 전문가의 도움이

### Evaluation

In [15]:
from nltk.translate.meteor_score import meteor_score
from nltk.tokenize import word_tokenize
import nltk
nltk.download('wordnet')
nltk.download('punkt')

def evaluate_meteor(model, test_dataset):
    scores = []
    
    for sample in test_dataset:
        # 모델 출력 생성
        generated = model.generate(sample['instruction'])
        reference = sample['output']
        
        # 토크나이징 (한국어는 형태소 분석기 권장)
        gen_tokens = word_tokenize(generated)
        ref_tokens = word_tokenize(reference)
        
        score = meteor_score([ref_tokens], gen_tokens)
        scores.append(score)
    
    return sum(scores) / len(scores)

# 각 모델별 점수 비교
kogpt2_score = evaluate_meteor(kogpt2_model, test_data)
sft_score    = evaluate_meteor(sft_model, test_data)
rm_score     = evaluate_meteor(rm_model, test_data)

print(f"KoGPT2 METEOR : {kogpt2_score:.4f}")
print(f"SFT    METEOR : {sft_score:.4f}")
print(f"RM     METEOR : {rm_score:.4f}")

ModuleNotFoundError: No module named 'nltk'

In [17]:
from konlpy.tag import Okt
okt = Okt()

def korean_tokenize(text):
    return okt.morphs(text)  # 형태소 단위 분리
```

---

### 3. 🆚 A/B 비교 평가 설계

#### 평가 시트 구성
```
질문: "건강한 식습관을 위한 팁을 알려주세요"

[Model A 응답]
"채소와 과일을 충분히 섭취하고, 규칙적인 
식사 시간을 지키는 것이 중요합니다."

[Model B 응답]  
"건강한 식단 식단 식단을 위해 식단..."

→ 어느 쪽이 더 나은 답변인가?
   ☐ A가 훨씬 낫다
   ☐ A가 약간 낫다  
   ☐ 비슷하다
   ☐ B가 약간 낫다
   ☐ B가 훨씬 낫다

SyntaxError: unterminated string literal (detected at line 17) (121461031.py, line 17)

In [18]:
results = {
    "A_much_better": 12,
    "A_slightly_better": 8,
    "tie": 5,
    "B_slightly_better": 3,
    "B_much_better": 2
}

# Win Rate 계산
total = sum(results.values())
a_win = (results["A_much_better"] + results["A_slightly_better"]) / total
print(f"A Win Rate: {a_win:.1%}")  # ex) 66.7%
```

---

### 전체 실험 흐름 요약
```
원본 데이터셋
    ↓ 정제 (중복/노이즈/불일치 제거)
정제된 데이터셋
    ↓
KoGPT2 / SFT 모델 / RM 모델 각각 inference
    ↓
정량: METEOR 점수 비교 (수치)
정성: A/B 비교 평가 (Win Rate)
    ↓
결론: 어떤 모델/데이터가 가장 효과적인가?

SyntaxError: invalid character '↓' (U+2193) (167183541.py, line 20)

### Huggingface transformers 설계구조

- [ ] Processors: task를 정의하고 dataset을 알맞게 가공
- [x] Tokenizer : 텍스트 데이터를 전처리
- [x] Model: 다양한 model을 정의
- [ ] Optimization : optimizer와 학습 schedule(warm up 등)을 관리
- [x] Trainer : 학습 과정을 전반을 관리
- [x] Config : weight와 tokenizer, model을 쉽게 불러올 수 있도록 각종 설정을 저장

### (1) Model

- huggingface에서 pretrained model 불러오기
  - [pretrained models](https://huggingface.co/transformers/v4.11.3/pretrained_models.html)
  ```
  model = aaa.from_pretrained('bbb')
      aaa : 모델구조
      bbb : 사전학습 모델(weight)
  ```
- 직접 학습시킨 모델 불러오기
  - config + 모델 저장 경로

In [9]:
from transformers import BertForPreTraining
model = BertForPreTraining.from_pretrained('bert-base-cased')

print(model.__class__)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/206 [00:00<?, ?it/s]

<class 'transformers.models.bert.modeling_bert.BertForPreTraining'>

In [10]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-cased")
print(model.__class__)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

<class 'transformers.models.bert.modeling_bert.BertModel'>

### (2) Tokenizer

- huggingface에서 pretrained model 불러오기
  ```
  model = aaa.from_pretrained('bbb')
      aaa : 토크나이저
      bbb : 사전학습 모델(weight)
  ```

In [11]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [12]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

In [26]:
#1개 문장 토크나이저
sentence = "This is Test for aiffel"

encoded = tokenizer(sentence) #모델 입력 형태로 변환 - 토큰 번호, 실제 토큰 위치, 문장 구분
print(encoded)

tokens = tokenizer.tokenize(sentence) #문장을 토큰으로만 분리/ 문장 1개만 입력받음
print(tokens)

{'input_ids': [101, 1188, 1110, 5960, 1111, 170, 11093, 1883, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
['This', 'is', 'Test', 'for', 'a', '##iff', '##el']

In [29]:
#문장 여러개(배치) 토크나이저
batch_sentences = ["Hello I'm a single sentence",
                    "And another sentence",
                    "And the very very last one"]

encoded_batch = tokenizer(batch_sentences)
print(encoded_batch)

tokens_batch = tokens_batch = [tokenizer.tokenize(s) for s in batch_sentences] #문장 여러개
print(tokens_batch)

{'input_ids': [[101, 8667, 146, 112, 182, 170, 1423, 5650, 102], [101, 1262, 1330, 5650, 102], [101, 1262, 1103, 1304, 1304, 1314, 1141, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}
[['Hello', 'I', "'", 'm', 'a', 'single', 'sentence'], ['And', 'another', 'sentence'], ['And', 'the', 'very', 'very', 'last', 'one']]

In [30]:
# 토크나이저+가장 긴 문장길이에 맞게 padding

batch = tokenizer(batch_sentences, padding=True, truncation=True, return_tensors="pt") #truncation = True?문장이 모델 최대 길이보다 길면 잘라냄, pt: 파이토치 텐서로 반환
print(batch)

{'input_ids': tensor([[ 101, 8667,  146,  112,  182,  170, 1423, 5650,  102],
        [ 101, 1262, 1330, 5650,  102,    0,    0,    0,    0],
        [ 101, 1262, 1103, 1304, 1304, 1314, 1141,  102,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0]])}

### (3) Config
- 모델을 학습시키기 위한 요소들을 명시한 json파일
  - train에 필요한 요소 : batch size, learning rate, weight_decay
  - tokenizer의 특수토큰(ex. [MASK])
- 설정변경, 나만의 모델 학십시에는 config파일을 직접 불러와야 함
- pretrained 모델 불러오기
  ```
  config = aaa.from_pretrained("bbb")
  aaa : config 모델
  bbb : 사전학습 모델(weight)
  ```

In [17]:
from transformers import BertConfig

config = BertConfig.from_pretrained("bert-base-cased")
print(config.__class__)
print(config)

<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

In [18]:
from transformers import AutoConfig

config = AutoConfig.from_pretrained("bert-base-cased")
print(config.__class__)
print(config)

<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

In [19]:
model = BertForPreTraining.from_pretrained('bert-base-cased')

# Q. 생성된 모델에서 config를 가져와봅시다
config = model.config

print(config)

Loading weights:   0%|          | 0/206 [00:00<?, ?it/s]

BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

### (4) Trainer

- training, fine-tuning, evaluation 수행

In [20]:
## colab에서 datasets을 설치
!pip install datasets

Collecting datasets
  Downloading datasets-4.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.2.6)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from datasets) (2.3.0)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.19 (from datasets)
  Downloading multiprocess-0.70.18-py312-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.5.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (1.7.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.12/site-packages (from datasets) (6.0.2)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.14.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Downloading datasets-4.7.0-py3-none-any.whl (527 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.5/527.5 kB 13.7 MB/s eta 0:00:00
Downloading multiprocess-0.70.18-py312-none-any.whl (150 kB)
Downloading aiohttp-3.13.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 47.7 MB/s eta 0:00:00
Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Downloading yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (100 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (221 kB)
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 94.4 MB/s eta 0:00:00:00:0100:01
Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Installing collected packages: xxhash, pyarrow, propcache, multiprocess, multidict, frozenlist, aiohappyeyeballs, yarl, aiosignal, aiohttp, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 20.0.0
    Uninstalling pyarrow-20.0.0:
      Successfully uninstalled pyarrow-20.0.0━━━━━━━━━━━━━━━━━━━━━  1/11 [pyarrow]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [datasets]/11 [datasets]ess]
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 datasets-4.7.0 frozenlist-1.8.0 multidict-6.7.1 multiprocess-0.70.18 propcache-0.4.1 pyarrow-23.0.1 xxhash-3.6.0 yarl-1.23.0

In [31]:
!pip install --upgrade pyarrow #커널 재시작

Requirement already satisfied: pyarrow in /opt/conda/lib/python3.12/site-packages (23.0.1)

In [1]:
from datasets import load_dataset
from transformers import AutoTokenizer, TrainingArguments, Trainer, AutoModelForSequenceClassification

raw_datasets = load_dataset("glue", "cola") #GLUE Benchmark의 CoLA 데이터셋: 문장이 문법적으로 맞는지 판단
checkpoint = "bert-base-uncased" #bert abse 모델. 12 layers, 768 hidden size, 12 attention heads, 110M parameters
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

raw_datasets

README.md: 0.00B [00:00, ?B/s]

cola/train-00000-of-00001.parquet:   0%|          | 0.00/251k [00:00<?, ?B/s]

cola/validation-00000-of-00001.parquet:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

cola/test-00000-of-00001.parquet:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8551 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1043 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1063 [00:00<?, ? examples/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 8551
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1043
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1063
    })
})

In [4]:
model_name_or_path = "bert-base-uncased"
model = AutoModelForSequenceClassification.from_pretrained(model_name_or_path, num_labels=2)    # COLA dataset의 라벨은 0(unacceptable)과 1(accpetable) 두 가지로 구분됨
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)

#문장만 불러와서 토크나이서 실행
def tokenize_function(example):
    return tokenizer(example["sentence"], truncation=True)

tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/8551 [00:00<?, ? examples/s]

Map:   0%|          | 0/1043 [00:00<?, ? examples/s]

Map:   0%|          | 0/1063 [00:00<?, ? examples/s]

In [6]:
# Trainer에게 전달할 학습 환경 설정 객체
training_args = TrainingArguments(
    output_dir='./results',              # output이 저장될 경로
    num_train_epochs=1,              # train 시킬 총 epochs
    per_device_train_batch_size=16,  # 각 device 당 batch size
    per_device_eval_batch_size=64,   # evaluation 시에 batch size
    warmup_steps=500,                # learning rate scheduler에 따른 warmup_step 설정
    weight_decay=0.01,                 # weight decay
    logging_dir='./logs',                 # log가 저장될 경로
    do_train=True,                        # train 수행여부
    do_eval=True,                        # eval 수행여부
    eval_steps=1000,
    #group_by_length=False,          #group_by_length은 학습 과정을 효율화하는 기능이 있다. 이유는 무엇일까? 길이가 비슷한 문장끼리 그룹핑해서 padding이 줄어든다!! 
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [7]:
### 현재 설치된 transformers 버전에서는 tokenizer를 Trainer에 직접 전달할 수 없음
'''
trainer = Trainer(
    model,                                                                    # 학습시킬 model
    args=training_args,                                                # TrainingArguments을 통해 설정한 arguments
    train_dataset=tokenized_datasets["train"],         # training dataset
    eval_dataset=tokenized_datasets["validation"], # validation dataset
    tokenizer=tokenizer, 
)

# 모델 학습
trainer.train()
'''

TypeError: Trainer.__init__() got an unexpected keyword argument 'tokenizer'

In [8]:
from transformers import DataCollatorWithPadding, Trainer

# padding 및 batch 처리를 위해 DataCollator 사용
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator
)

In [9]:
# 모델 학습
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=535, training_loss=0.5292082135922441, metrics={'train_runtime': 59.4958, 'train_samples_per_second': 143.724, 'train_steps_per_second': 8.992, 'total_flos': 91092439031580.0, 'train_loss': 0.5292082135922441, 'epoch': 1.0})